"""1217 - emit the Lean data module C1GateMatrixBoxData.lean from the
certified bundle 1217_m_boxes_cert.json (prereg 1217; do not edit the
generated module by hand - regenerate).

Validations (exact Fractions) BEFORE emitting:
  * all 64 entries present with lo <= hi, widths <= 1e-9 on the 20
    same-parity independent entries (falsifier (a) at the data level);
  * mixed-parity entries: the numeric mid is consistent with the D1
    exact zero (|mid| <= max(budget, 1e-9)) - the emitted mixed boxes
    are EXACT [0, 0] (owned by the Lean theorem gateMatrix_zero_of_odd,
    not by the numerics);
  * symmetry cross-check |mid_ij - mid_ji| <= 2 max(budgets).
"""
import json
import os
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
CERT = os.path.join(HERE, "1217_m_boxes_cert.json")
DEV = os.path.join(HERE, "..", "..", "ConnesWeilRH", "Dev")
OUT = os.path.join(DEV, "C1GateMatrixBoxData.lean")

K = 8
DEN = 2 ** 72
WIDTH_CAP = Fraction(1, 10 ** 9)

cert = json.load(open(CERT))
entries = cert["entries"]
assert len(entries) == 64, len(entries)


def parity(i, j):
    return (i + j) % 2 == 0


worst_width = Fraction(0)
mixed_consistency = Fraction(0)
sym_worst = Fraction(0)
for i in range(K):
    for j in range(K):
        e = entries[f"{i},{j}"]
        lo, hi = Fraction(e["lo"]), Fraction(e["hi"])
        mid = Fraction(e["mid"])
        bud = Fraction(e["budget"])
        assert lo <= hi, (i, j)
        if parity(i, j):
            width = hi - lo
            assert width <= WIDTH_CAP, (i, j, float(width))
            worst_width = max(worst_width, width)
        else:
            mixed_consistency = max(mixed_consistency, abs(mid))
        if i < j:
            other = Fraction(entries[f"{j},{i}"]["mid"])
            bound = 2 * max(bud, Fraction(entries[f"{j},{i}"]["budget"]))
            assert abs(mid - other) <= bound, (i, j)
            sym_worst = max(sym_worst, abs(mid - other))

print(f"validation OK: worst same-parity width = {float(worst_width):.3e}")
print(f"mixed consistency max |mid| = {float(mixed_consistency):.3e}")
print(f"symmetry cross-check max |M_ij - M_ji| = {float(sym_worst):.3e}")

# regression cross-check: record 1216 verified the certified formula
# against the committed 1112 same-parity values to 1.4e-12; the engine
# must reproduce them at the certified scale (catches domain/slip bugs
# that convergence gates cannot see - e.g. the (0,8) domain slip).
d1112 = json.load(open(os.path.join(HERE, "1112_cert.json")))["classes"][0]
worst_reg = Fraction(0)
for i in range(K):
    for j in range(K):
        if parity(i, j):
            committed = Fraction(d1112["M_mid"][i][j])
            dev = abs(Fraction(entries[f"{i},{j}"]["mid"]) - committed)
            worst_reg = max(worst_reg, dev)
            assert dev <= Fraction(5, 10 ** 9), (i, j, float(dev))
print(f"regression cross-check vs 1112 M_mid: worst {float(worst_reg):.3e}")

wh = cert.get("whitened_check", {})
assert wh.get("pass") is True, f"falsifier B not PASSED: {wh}"
print(f"falsifier B PASS: top + infl = {wh['top_plus_inflation']:.6e} "
      f"<= U - 1e-8 = {wh['U'] - 1e-8:.6e}")

# the 20 same-parity independent entries (12 off-diagonal + 8 diagonal)
same_ind = [(i, j) for i in range(K) for j in range(i, K) if parity(i, j)]
print(f"same-parity independent entries: {len(same_ind)}")


def matrix_literal(choose):
    rows = []
    for i in range(K):
        vals = []
        for j in range(K):
            v = choose(i, j)
            vals.append(f"({v.numerator}/{v.denominator} : ℝ)")
        rows.append("    " + ", ".join(vals) + (";" if i < K - 1 else ""))
    return "!![\n" + "\n".join(rows) + "\n  ]"


def lo_of(i, j):
    if parity(i, j):
        return Fraction(entries[f"{i},{j}"]["lo"])
    return Fraction(0)


def hi_of(i, j):
    if parity(i, j):
        return Fraction(entries[f"{i},{j}"]["hi"])
    return Fraction(0)


header = """/-
Copyright (c) 2026 ConnesWeilRH contributors. All rights reserved.
Released under the Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Dev.C1GateMatrixParity

/-!
# Record 1217: certified boxes for the true class (2,8) gate matrix

GENERATED by docs/proofs/1217_emit_box_data.py from docs/proofs/
1217_m_boxes_cert.json (do not edit by hand - regenerate).  Prereg:
1217_m_side_box_certificate_preregistration.md (committed a32e53e
before the run).

- mixed-parity entries (i + j odd): EXACT [0, 0] boxes, owned by the
  Lean parity theorem gateMatrix_zero_of_odd (record 1215 D1, landed
  in C1GateMatrixParity) - the numerics only cross-check them;
- same-parity entries: outward dyadic boxes (denominator 2^72) from
  the certified quadrature, entry budgets <= 5e-10, worst certified
  width {worst_width} <= 1e-9, gates |GL_n - GL_(n/2)| <= 1e-12 at
  every required point, whitened-top inflation check recorded in the
  JSON.

The same-parity containment is NOT discharged here: it is consumed as
the named hypothesis of q28_hboxM_of_sameParity (the entrywise
envelope campaign is the registered follow-up).  RH NOT claimed.
-/

namespace ConnesWeilRH
namespace Source
namespace C1GateMatrixBoxData

open Matrix
open C1ClassWindowObjects
open C1GateMatrixRepresentation

-- Generated exact-rational data lines cannot fit 100 columns (house
-- convention for machine-generated data modules).
set_option linter.style.longLine false

noncomputable section

/-- Certified lower box for the true gate matrix (mixed entries exact
zeros). -/
def MLo_q28M : Matrix (Fin 8) (Fin 8) ℝ :=
  {lo_literal}

/-- Certified upper box for the true gate matrix. -/
def MHi_q28M : Matrix (Fin 8) (Fin 8) ℝ :=
  {hi_literal}

/-- Data fact: every mixed-parity box is the exact-zero pair. -/
theorem zero_box_odd_data : ∀ i j : Fin 8, Odd ((i : ℕ) + (j : ℕ)) →
    MLo_q28M i j = 0 ∧ MHi_q28M i j = 0 := by
  intro i j hodd
  fin_cases i <;> fin_cases j
  all_goals
    rcases hodd with ⟨k, hk⟩
    have hmod := congrArg (fun n : ℕ => n % 2) hk
    norm_num [Nat.add_mod, Nat.mul_mod] at hmod
    all_goals simp [MLo_q28M, MHi_q28M]

/-- The mixed-parity gate matrix entries sit in their boxes, by D1. -/
theorem gateMatrix_mem_zero_box_of_odd (a : ℝ) (ha : 0 < a) (i j : Fin 8)
    (hodd : Odd ((i : ℕ) + (j : ℕ))) :
    MLo_q28M i j ≤ gateMatrix (classTestFamily a ha) i j ∧
      gateMatrix (classTestFamily a ha) i j ≤ MHi_q28M i j := by
  rw [C1GateMatrixParity.gateMatrix_zero_of_odd a ha i j hodd]
  obtain ⟨h1, h2⟩ := zero_box_odd_data i j hodd
  constructor
  · rw [h1]
    exact le_refl 0
  · rw [h2]
    exact le_refl 0

/-- D5 binding: given the same-parity enclosures (the registered
follow-up campaign), the certified box contains the true gate matrix
entrywise. -/
theorem q28_hboxM_of_sameParity (a : ℝ) (ha : 0 < a)
    (hsp : ∀ i j : Fin 8, Even ((i : ℕ) + (j : ℕ)) →
      MLo_q28M i j ≤ gateMatrix (classTestFamily a ha) i j ∧
        gateMatrix (classTestFamily a ha) i j ≤ MHi_q28M i j) :
    ∀ i j : Fin 8, MLo_q28M i j ≤
        gateMatrix (classTestFamily a ha) i j ∧
      gateMatrix (classTestFamily a ha) i j ≤ MHi_q28M i j := by
  intro i j
  rcases Nat.even_or_odd ((i : ℕ) + (j : ℕ)) with hev | hod
  · exact hsp i j hev
  · exact gateMatrix_mem_zero_box_of_odd a ha i j hod

end
end C1GateMatrixBoxData
end Source
end ConnesWeilRH
"""

body = (header
        .replace("{worst_width}", f"{float(worst_width):.3e}")
        .replace("{lo_literal}", matrix_literal(lo_of))
        .replace("{hi_literal}", matrix_literal(hi_of)))
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(body)
print(f"WROTE {OUT} ({len(body)} bytes)")
