#!/usr/bin/env python3
"""Finite certificate for Proof 417's exponential-tilt guard."""

from __future__ import annotations

import argparse
import math

import numpy as np


def projection(vector: np.ndarray) -> np.ndarray:
    """Return the rank-one orthogonal projection generated by vector."""
    normalized = vector / np.linalg.norm(vector)
    return np.outer(normalized, normalized.conj())


def commutator(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    return left @ right - right @ left


def tilted_projection(scale: float, epsilon: float, time: float) -> np.ndarray:
    base_vector = np.array(
        [math.sqrt(1.0 - epsilon), math.sqrt(epsilon)], dtype=np.float64
    )
    tilted_vector = np.array(
        [base_vector[0], math.exp(0.5 * time * scale) * base_vector[1]],
        dtype=np.float64,
    )
    return projection(tilted_vector)


def compression_phi_twice(scale: float, epsilon: float) -> float:
    gram = 1.0 - epsilon + epsilon * math.exp(2.0 * scale)
    linear_term = 2.0 * scale * epsilon
    return math.log(gram) - linear_term


def run_scale(scale: float, quadrature_order: int) -> dict[str, float]:
    epsilon = math.exp(-scale)
    base_projection = tilted_projection(scale, epsilon, 0.0)
    endpoint_projection = tilted_projection(scale, epsilon, 1.0)
    generator = np.diag([0.0, scale])
    detector = np.diag([0.0, 1.0])

    response = float(np.trace(detector @ (endpoint_projection - base_projection)))
    expected_response = 1.0 / (2.0 - epsilon) - epsilon
    commutator_product = float(
        np.linalg.norm(commutator(generator, base_projection), ord="fro")
        * np.linalg.norm(commutator(detector, base_projection), ord="fro")
    )

    nodes, weights = np.polynomial.legendre.leggauss(quadrature_order)
    path_covariance = 0.0
    path_generator_variance = 0.0
    maximum_detector_variance = 0.0
    for node, weight in zip(nodes, weights, strict=True):
        time = 0.5 * (node + 1.0)
        path_projection = tilted_projection(scale, epsilon, time)
        complement = np.eye(2) - path_projection
        covariance = np.trace(
            path_projection
            @ generator
            @ complement
            @ detector
            @ path_projection
        ).real
        generator_variance = np.trace(
            path_projection
            @ generator
            @ complement
            @ generator
            @ path_projection
        ).real
        detector_variance = np.trace(
            path_projection
            @ detector
            @ complement
            @ detector
            @ path_projection
        ).real
        path_covariance += 0.5 * weight * covariance
        path_generator_variance += 0.5 * weight * generator_variance
        maximum_detector_variance = max(
            maximum_detector_variance, float(detector_variance)
        )

    symmetric_tilt_energy = scale * expected_response
    phi_twice = compression_phi_twice(scale, epsilon)
    entropy_bound = math.sqrt(0.25 * phi_twice)
    exponential_endpoint_bound = (
        math.exp(scale) * commutator_product / math.sqrt(2.0)
    )

    return {
        "scale": scale,
        "response": response,
        "response_error": abs(response - expected_response),
        "commutator_product": commutator_product,
        "required_constant": response / commutator_product,
        "path_error": abs(path_covariance - response),
        "energy_error": abs(path_generator_variance - symmetric_tilt_energy),
        "entropy_slack": phi_twice - symmetric_tilt_energy,
        "entropy_bound_slack": entropy_bound - response,
        "endpoint_bound_slack": exponential_endpoint_bound - response,
        "sampled_variance_gap": 0.25 - maximum_detector_variance,
    }


def parse_scales(value: str) -> list[float]:
    scales = [float(part.strip()) for part in value.split(",") if part.strip()]
    if not scales or any(scale < 2.0 for scale in scales):
        raise argparse.ArgumentTypeError("all scales must be at least 2")
    return scales


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scales", type=parse_scales, default=parse_scales("2,4,8,12"))
    parser.add_argument("--quadrature-order", type=int, default=256)
    args = parser.parse_args()

    rows = [run_scale(scale, args.quadrature_order) for scale in args.scales]

    print("+-------+---------------+---------------+---------------+---------------+")
    print("| scale | response      | comm product  | required C    | path error    |")
    print("+-------+---------------+---------------+---------------+---------------+")
    for row in rows:
        print(
            f"| {row['scale']:5.1f} | {row['response']:13.6e} | "
            f"{row['commutator_product']:13.6e} | "
            f"{row['required_constant']:13.6e} | {row['path_error']:13.6e} |"
        )
    print("+-------+---------------+---------------+---------------+---------------+")

    maximum_response_error = max(row["response_error"] for row in rows)
    maximum_path_error = max(row["path_error"] for row in rows)
    maximum_energy_error = max(row["energy_error"] for row in rows)
    minimum_entropy_slack = min(row["entropy_slack"] for row in rows)
    minimum_entropy_bound_slack = min(row["entropy_bound_slack"] for row in rows)
    minimum_endpoint_bound_slack = min(row["endpoint_bound_slack"] for row in rows)
    required_constant_growth = (
        rows[-1]["required_constant"] / rows[0]["required_constant"]
    )

    print(f"maximum_response_error={maximum_response_error:.12e}")
    print(f"maximum_path_error={maximum_path_error:.12e}")
    print(f"maximum_energy_error={maximum_energy_error:.12e}")
    print(f"minimum_entropy_slack={minimum_entropy_slack:.12e}")
    print(f"minimum_entropy_bound_slack={minimum_entropy_bound_slack:.12e}")
    print(f"minimum_endpoint_bound_slack={minimum_endpoint_bound_slack:.12e}")
    print(f"required_constant_growth={required_constant_growth:.12e}")
    print("fixed_endpoint_commutator_product=REJECTED_ANALYTICALLY")
    print("tilted_path_entropy_bound=VERIFIED_FINITE")
    print("localized_continuous_entropy=OPEN")
    print("gate_3u=OPEN")
    print("RH=UNPROVED")

    tolerance = 5.0e-12
    if maximum_response_error > tolerance:
        raise SystemExit("rank-one response identity failed")
    if maximum_path_error > tolerance or maximum_energy_error > tolerance:
        raise SystemExit("tilted-path integral identity failed")
    if minimum_entropy_slack < -tolerance:
        raise SystemExit("symmetric tilt energy exceeded Phi(2A)")
    if minimum_entropy_bound_slack < -tolerance:
        raise SystemExit("entropy response bound failed")
    if minimum_endpoint_bound_slack < -tolerance:
        raise SystemExit("condition-dependent endpoint bound failed")
    if required_constant_growth < 100.0:
        raise SystemExit("counterexample cohort did not expose constant growth")


if __name__ == "__main__":
    main()
