import ConnesWeilRH.Dev.C1C3CarrierFourierShift

namespace ConnesWeilRH
namespace Dev
namespace C1C3CarrierTransport

#print axioms c3FourierIntegral
#print axioms c3CarrierFourierIntegral
#print axioms c3CarrierFourierIntegral_eq_frequency_shift
#print axioms c3CarrierFourierIntegral_zero_frequency_shift

end C1C3CarrierTransport
end Dev
end ConnesWeilRH
