import ConnesWeilRH.Dev.C1CC20FiniteRankGapCertificate

namespace ConnesWeilRH.Source.C1CC20FiniteRankGapCertificate

#check norm_toLp_eq_integral_norm_rpow_half
#check l2Mass_cc20WindowZeroExtend_le
#check integral_norm_sq_cc20WindowZeroExtend_star_eq
#check CC20FiniteRankGapCertificate
#check norm_inner_applyKernelLp_cc20FiniteRankDifference_le_of_certificate
#check cc20FiniteRankGap_pairingBound_of_certificate
#check cc20FiniteRankGapNorm_le_of_certificate
#check cc20FiniteRankNegativeForm_le_rankOne_of_certificate

#print axioms norm_toLp_eq_integral_norm_rpow_half
#print axioms l2Mass_cc20WindowZeroExtend_le
#print axioms integral_norm_sq_cc20WindowZeroExtend_star_eq
#print axioms norm_inner_applyKernelLp_cc20FiniteRankDifference_le_of_certificate
#print axioms cc20FiniteRankGap_pairingBound_of_certificate
#print axioms cc20FiniteRankGapNorm_le_of_certificate
#print axioms cc20FiniteRankNegativeForm_le_rankOne_of_certificate

end ConnesWeilRH.Source.C1CC20FiniteRankGapCertificate
