import ConnesWeilRH.Dev.C1DigammaDerivativeSeries

namespace ConnesWeilRH
namespace Dev

#check @hasDerivAt_halfAnchorReciprocalSeries_of_re_ge_quarter
#print axioms hasDerivAt_halfAnchorReciprocalSeries_of_re_ge_quarter
#check @hasDerivAt_digamma_of_re_ge_quarter
#print axioms hasDerivAt_digamma_of_re_ge_quarter
#check @quarter_series_tsum_le_twenty
#check @norm_digamma_deriv_le_twenty
#print axioms quarter_series_tsum_le_twenty
#print axioms norm_digamma_deriv_le_twenty

end Dev
end ConnesWeilRH
