/-
Copyright (c) 2026 ConnesWeilRH contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Dev.C1G8R3BoundaryOutputFactorizationBridge

namespace ConnesWeilRH
namespace Dev

#check @suffixEulerBoundaryOutputMaps_cons_head_factorization
#print axioms suffixEulerBoundaryOutputMaps_cons_head_factorization
#check @suffixEulerBoundaryOutputMaps_factorization
#print axioms suffixEulerBoundaryOutputMaps_factorization
#check @finiteEulerMetricCoframeBoundaryMaps_factorization
#print axioms finiteEulerMetricCoframeBoundaryMaps_factorization
#check @g8AmbientSourceLeg_energy_normSq_split
#print axioms g8AmbientSourceLeg_energy_normSq_split
#check @g8AmbientSourceLeg_outLeg_pointwise_eq_boundary_add_gap
#print axioms g8AmbientSourceLeg_outLeg_pointwise_eq_boundary_add_gap
#check @g8AmbientSourceLeg_gapLeg_pointwise_eq_sourceRange_add_complement
#print axioms g8AmbientSourceLeg_gapLeg_pointwise_eq_sourceRange_add_complement
#check @sourceSoninComplement_comp_ambientFactor_comp_sourceInclusion_eq_commutator
#print axioms sourceSoninComplement_comp_ambientFactor_comp_sourceInclusion_eq_commutator
#check @sourceSoninComplement_comp_commutator_sourceRange_eq_zero
#print axioms sourceSoninComplement_comp_commutator_sourceRange_eq_zero
#check @sourceSoninComplement_comp_commutator_sourceOrthogonal_eq
#print axioms sourceSoninComplement_comp_commutator_sourceOrthogonal_eq
#check @sourceFourierSupportProjection_comp_sourceInclusion_eq_self
#print axioms sourceFourierSupportProjection_comp_sourceInclusion_eq_self
#check @sourceSoninOuterPair_comp_sourceInclusion_expanded
#print axioms sourceSoninOuterPair_comp_sourceInclusion_expanded
#check @sourceSoninOuterPair_comp_sourceInclusion_eq_radialLeakage
#print axioms sourceSoninOuterPair_comp_sourceInclusion_eq_radialLeakage
#check @sourceSoninOuterPair_sourceBasis_normSq_summable_of_radialLeakage
#print axioms sourceSoninOuterPair_sourceBasis_normSq_summable_of_radialLeakage
#check @sourceSoninOuterSecondReflected_comp_sourceInclusion_eq_hardySubId
#print axioms sourceSoninOuterSecondReflected_comp_sourceInclusion_eq_hardySubId
#check @sourceSoninHardySubId_comp_sourceInclusion_eq_radial_fourierDefect
#print axioms sourceSoninHardySubId_comp_sourceInclusion_eq_radial_fourierDefect
#check @sourceSoninHardyFourierGap_comp_sourceInclusion_eq_hardyRadialLeakage
#print axioms sourceSoninHardyFourierGap_comp_sourceInclusion_eq_hardyRadialLeakage
#check @sourceSoninHardySubId_sourceBasis_normSq_summable_of_radial_fourierDefects
#print axioms sourceSoninHardySubId_sourceBasis_normSq_summable_of_radial_fourierDefects
#check @sourceSoninHardySubId_sourceBasis_normSq_summable_of_sourceRadialSupport
#print axioms sourceSoninHardySubId_sourceBasis_normSq_summable_of_sourceRadialSupport
#check @sourceSoninCommutator_comp_sourceInclusion_eq_hardySubId_sub_prolate
#print axioms sourceSoninCommutator_comp_sourceInclusion_eq_hardySubId_sub_prolate
#check @sourceSoninCommutator_sourceBasis_normSq_summable_of_hardySubId_prolate
#print axioms sourceSoninCommutator_sourceBasis_normSq_summable_of_hardySubId_prolate
#check @sourceProlateCommutator_sourceBasis_normSq_summable_of_factor
#print axioms sourceProlateCommutator_sourceBasis_normSq_summable_of_factor
#check @sourceSoninCommutator_sourceBasis_normSq_summable_of_hardySubId_factor
#print axioms sourceSoninCommutator_sourceBasis_normSq_summable_of_hardySubId_factor
#check @sourceSoninCommutator_eq_threeBranch
#print axioms sourceSoninCommutator_eq_threeBranch
#check @sourceBasis_normSq_summable_of_three_add_sub
#print axioms sourceBasis_normSq_summable_of_three_add_sub
#check @sourceSoninCommutator_sourceBasis_normSq_summable_of_threeBranch
#print axioms sourceSoninCommutator_sourceBasis_normSq_summable_of_threeBranch
#check @sourceSoninCommutator_sourceBasis_normSq_summable_of_outerPair_remainder
#print axioms sourceSoninCommutator_sourceBasis_normSq_summable_of_outerPair_remainder
#check @ambientProduct_commutator_eq_leibniz_sum
#print axioms ambientProduct_commutator_eq_leibniz_sum
#check @ambientProduct_commutator_sourceBasis_normSq_summable_of_leibniz
#print axioms ambientProduct_commutator_sourceBasis_normSq_summable_of_leibniz
#check @g8AmbientSourceLeg_inLeg_normSq_summable_of_energy
#print axioms g8AmbientSourceLeg_inLeg_normSq_summable_of_energy
#check @g8AmbientSourceLeg_energy_normSq_summable_of_legs
#print axioms g8AmbientSourceLeg_energy_normSq_summable_of_legs
#check @g8MetricVisibleBoundary_root_energy_summable_of_legs
#print axioms g8MetricVisibleBoundary_root_energy_summable_of_legs

end Dev
end ConnesWeilRH
