import ConnesWeilRH.Dev.C1G8R5AggregateExpansion

namespace ConnesWeilRH
namespace Dev
namespace C1G8R5AggregateExpansionAudit

#print axioms g8AmbientRootAggregate
#print axioms g8AmbientRootAggregate_isPositive
#print axioms g8EndpointSourceCutoffLimitOperator_eq_sourceCompression_ambientRootAggregate
#print axioms g8AmbientRootAggregate_eq_fourTerms
#print axioms g8EndpointSourceCutoffLimitOperator_isPositive
#print axioms g8AmbientArithmeticCorrection
#print axioms g8AmbientArithmeticCorrection_adjoint_eq
#print axioms trace_basisPrefixMatrix_g8AmbientArithmeticCorrection_im_eq_zero
#print axioms g8AmbientRootAggregate_eq_rootSandwiched_add_correction
#print axioms g8EndpointSourceCutoffLimitOperator_eq_sourceCompression_rootResponse_add_correction
#print axioms trace_basisPrefixMatrix_g8AmbientRootAggregate_eq_rootResponse_add_correction
#print axioms trace_basisPrefixMatrix_g8AmbientRootAggregate_eq_arithmetic_add_residual_add_correction
#print axioms ordinaryTraceAlong_g8ArithmeticOperator_eq_finitePrimeTerm_sum
#print axioms g8EndpointSourceCutoffLimitOperator_eq_fourTerms
#print axioms qw_nonnegative_of_g8_survivorCore_and_aggregate_eq

end C1G8R5AggregateExpansionAudit
end Dev
end ConnesWeilRH
