import ConnesWeilRH.Dev.C1G8R3WeightedFiniteStage

namespace ConnesWeilRH.Dev.C1G8R3WeightedFiniteStageAudit

#check operatorCommutator
#print axioms operatorCommutator
#check weightedCommutatorStage
#print axioms weightedCommutatorStage
#check weightedCommutatorStage_succ
#print axioms weightedCommutatorStage_succ
#check operator_pow_commutator_eq_weightedStage
#print axioms operator_pow_commutator_eq_weightedStage
#check doubledShiftRadialProjection
#print axioms doubledShiftRadialProjection
#check doubledShiftRadialProjection_isStarProjection
#print axioms doubledShiftRadialProjection_isStarProjection
#check doubledShiftAlternatingProduct
#print axioms doubledShiftAlternatingProduct
#check doubledShiftAlternatingProduct_isPositive
#print axioms doubledShiftAlternatingProduct_isPositive
#check doubledShiftAlternatingProduct_isSelfAdjoint
#print axioms doubledShiftAlternatingProduct_isSelfAdjoint
#check doubledShiftAlternatingProduct_norm_le_one
#print axioms doubledShiftAlternatingProduct_norm_le_one
#check doubledShiftAlternatingProduct_fixed_of_mem_intersection
#print axioms doubledShiftAlternatingProduct_fixed_of_mem_intersection
#check doubledShiftAlternatingProduct_pow_apply_of_mem_intersection
#print axioms doubledShiftAlternatingProduct_pow_apply_of_mem_intersection
#check norm_pow_le_one_of_norm_le_one
#print axioms norm_pow_le_one_of_norm_le_one
#check weightedCommutatorStage_norm_le_of_contraction
#print axioms weightedCommutatorStage_norm_le_of_contraction
#check doubledShiftAlternatingProduct_commutator_stage
#print axioms doubledShiftAlternatingProduct_commutator_stage

end ConnesWeilRH.Dev.C1G8R3WeightedFiniteStageAudit
