import ConnesWeilRH.Dev.C1G8P1MetricChannels

namespace ConnesWeilRH.Dev.C1G8P1MetricChannelsAudit

open ConnesWeilRH.Source.C1G8P1MetricChannels

#print axioms g8MetricSurvivorCoframe
#print axioms g8MetricVisibleBoundaryCoframe
#print axioms g8MetricLeakageCoframe
#print axioms g8MetricLeakageCoframe_eq_sourcePhysicalCoframeLeakage
#print axioms finiteEulerTargetCommutatorResponse_eq_g8MetricLeakageCross
#print axioms g8MetricCutoffLeakageSourceCrossOperator
#print axioms g8MetricCutoffLeakageSourceCrossOperator_eq_literal_sandwich
#print axioms g8MetricCutoffLeakageSourceCrossOperator_eq_metric_sub_source
#print axioms g8MetricCutoffLeakageSourceCrossOperator_isTraceClassAlong
#print axioms g8MetricCutoffSourceLeakageCrossOperator
#print axioms g8MetricCutoffSourceLeakageCrossOperator_isTraceClassAlong
#print axioms finiteEulerMetricCoframe_eq_g8MetricSurvivor_add_visibleBoundary
#print axioms g8MetricCutoffChannel
#print axioms g8MetricCutoffChannelPairData
#print axioms g8MetricCutoffChannelPairData_traceProduct_eq
#print axioms g8MetricCutoffChannel_isTraceClassAlong
#print axioms g8PhysicalMetricCutoffOperator_eq_fourChannels
#print axioms ordinaryTraceAlong_g8PhysicalMetricCutoffOperator_eq_fourChannels
#print axioms g8PhysicalMetricCutoffOperator_isTraceClassAlong

end ConnesWeilRH.Dev.C1G8P1MetricChannelsAudit
