/-
Copyright (c) 2026 ConnesWeilRH contributors. All rights reserved.
Released under the Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Dev.C1GateMatrixParity

/-!
# Record 1217: certified boxes for the true class (2,8) gate matrix

GENERATED by docs/proofs/1217_emit_box_data.py from docs/proofs/
1217_m_boxes_cert.json (do not edit by hand - regenerate).  Prereg:
1217_m_side_box_certificate_preregistration.md (committed a32e53e
before the run).

- mixed-parity entries (i + j odd): EXACT [0, 0] boxes, owned by the
  Lean parity theorem gateMatrix_zero_of_odd (record 1215 D1, landed
  in C1GateMatrixParity) - the numerics only cross-check them;
- same-parity entries: outward dyadic boxes (denominator 2^72) from
  the certified quadrature, entry budgets <= 5e-10, worst certified
  width 2.395e-13 <= 1e-9, gates |GL_n - GL_(n/2)| <= 1e-12 at
  every required point, whitened-top inflation check recorded in the
  JSON.

The same-parity containment is NOT discharged here: it is consumed as
the named hypothesis of q28_hboxM_of_sameParity (the entrywise
envelope campaign is the registered follow-up).  RH NOT claimed.
-/

namespace ConnesWeilRH
namespace Source
namespace C1GateMatrixBoxData

open Matrix
open C1ClassWindowObjects
open C1GateMatrixRepresentation

-- Generated exact-rational data lines cannot fit 100 columns (house
-- convention for machine-generated data modules).
set_option linter.style.longLine false

noncomputable section

/-- Certified lower box for the true gate matrix (mixed entries exact
zeros). -/
def MLo_q28M : Matrix (Fin 8) (Fin 8) ℝ :=
  !![
    (4353730820158621523243/2361183241434822606848 : ℝ), (0/1 : ℝ), (-2112088453242220918317/4722366482869645213696 : ℝ), (0/1 : ℝ), (-48739559486751010957/4722366482869645213696 : ℝ), (0/1 : ℝ), (165682085527923876993/4722366482869645213696 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (-208045124307874780143/4722366482869645213696 : ℝ), (0/1 : ℝ), (134930588602430589215/4722366482869645213696 : ℝ), (0/1 : ℝ), (-15595038480002039847/4722366482869645213696 : ℝ), (0/1 : ℝ), (-3015114944734751441/1180591620717411303424 : ℝ);
    (-2112088453242220910749/4722366482869645213696 : ℝ), (0/1 : ℝ), (128068398342851310629/1180591620717411303424 : ℝ), (0/1 : ℝ), (5908948993186824039/2361183241434822606848 : ℝ), (0/1 : ℝ), (-10038915475855149263/1180591620717411303424 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (4216580893825955927/147573952589676412928 : ℝ), (0/1 : ℝ), (-5469816265087210501/295147905179352825856 : ℝ), (0/1 : ℝ), (5052114140743512213/2361183241434822606848 : ℝ), (0/1 : ℝ), (7822465911731520891/4722366482869645213696 : ℝ);
    (-12184889871687757301/1180591620717411303424 : ℝ), (0/1 : ℝ), (369309312074176603/147573952589676412928 : ℝ), (0/1 : ℝ), (68037876588382845/1180591620717411303424 : ℝ), (0/1 : ℝ), (-115459510606606029/590295810358705651712 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (-7797519240001018449/2361183241434822606848 : ℝ), (0/1 : ℝ), (2526057070371756047/1180591620717411303424 : ℝ), (0/1 : ℝ), (-1188479113516137435/4722366482869645213696 : ℝ), (0/1 : ℝ), (-451925651667267697/2361183241434822606848 : ℝ);
    (82841042763961925037/2361183241434822606848 : ℝ), (0/1 : ℝ), (-40155661903420587657/4722366482869645213696 : ℝ), (0/1 : ℝ), (-923676084852847947/4722366482869645213696 : ℝ), (0/1 : ℝ), (780820535210404981/1180591620717411303424 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (-12060459778939003259/4722366482869645213696 : ℝ), (0/1 : ℝ), (7822465911731518553/4722366482869645213696 : ℝ), (0/1 : ℝ), (-112981412916817263/590295810358705651712 : ℝ), (0/1 : ℝ), (-2732997340653921/18446744073709551616 : ℝ)
  ]

/-- Certified upper box for the true gate matrix. -/
def MHi_q28M : Matrix (Fin 8) (Fin 8) ℝ :=
  !![
    (2176865410079593516949/1180591620717411303424 : ℝ), (0/1 : ℝ), (-528022113310285151807/1180591620717411303424 : ℝ), (0/1 : ℝ), (-48739559485689778521/4722366482869645213696 : ℝ), (0/1 : ℝ), (41420521382244962253/1180591620717411303424 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (-208045124306810509049/4722366482869645213696 : ℝ), (0/1 : ℝ), (67465294301746782595/2361183241434822606848 : ℝ), (0/1 : ℝ), (-7797519239471838365/2361183241434822606848 : ℝ), (0/1 : ℝ), (-12060459777883361571/4722366482869645213696 : ℝ);
    (-528022113310285149915/1180591620717411303424 : ℝ), (0/1 : ℝ), (256136796686235882585/2361183241434822606848 : ℝ), (0/1 : ℝ), (11817897987434681373/4722366482869645213696 : ℝ), (0/1 : ℝ), (-20077830951181650057/2361183241434822606848 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (134930588603493565639/4722366482869645213696 : ℝ), (0/1 : ℝ), (-87517060240332221349/4722366482869645213696 : ℝ), (0/1 : ℝ), (10104228282547041681/4722366482869645213696 : ℝ), (0/1 : ℝ), (122226029887319563/73786976294838206464 : ℝ);
    (-1523111233927806149/147573952589676412928 : ℝ), (0/1 : ℝ), (11817897987434684591/4722366482869645213696 : ℝ), (0/1 : ℝ), (34018938426847875/590295810358705651712 : ℝ), (0/1 : ℝ), (-461838041896830365/2361183241434822606848 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (-15595038478943673781/4722366482869645213696 : ℝ), (0/1 : ℝ), (5052114141273520721/2361183241434822606848 : ℝ), (0/1 : ℝ), (-1188479112455900567/4722366482869645213696 : ℝ), (0/1 : ℝ), (-451925651137968571/2361183241434822606848 : ℝ);
    (165682085528979822093/4722366482869645213696 : ℝ), (0/1 : ℝ), (-40155661902363290719/4722366482869645213696 : ℝ), (0/1 : ℝ), (-923676083793660445/4722366482869645213696 : ℝ), (0/1 : ℝ), (3123282141901174289/4722366482869645213696 : ℝ), (0/1 : ℝ);
    (0/1 : ℝ), (-6030229888941679533/2361183241434822606848 : ℝ), (0/1 : ℝ), (7822465912788449695/4722366482869645213696 : ℝ), (0/1 : ℝ), (-225962825568984963/1180591620717411303424 : ℝ), (0/1 : ℝ), (-699647318148367059/4722366482869645213696 : ℝ)
  ]

/-- Data fact: every mixed-parity box is the exact-zero pair. -/
theorem zero_box_odd_data : ∀ i j : Fin 8, Odd ((i : ℕ) + (j : ℕ)) →
    MLo_q28M i j = 0 ∧ MHi_q28M i j = 0 := by
  intro i j hodd
  fin_cases i <;> fin_cases j
  all_goals
    rcases hodd with ⟨k, hk⟩
    have hmod := congrArg (fun n : ℕ => n % 2) hk
    norm_num [Nat.add_mod, Nat.mul_mod] at hmod
    all_goals simp [MLo_q28M, MHi_q28M]

/-- The mixed-parity gate matrix entries sit in their boxes, by D1. -/
theorem gateMatrix_mem_zero_box_of_odd (a : ℝ) (ha : 0 < a) (i j : Fin 8)
    (hodd : Odd ((i : ℕ) + (j : ℕ))) :
    MLo_q28M i j ≤ gateMatrix (classTestFamily a ha) i j ∧
      gateMatrix (classTestFamily a ha) i j ≤ MHi_q28M i j := by
  rw [C1GateMatrixParity.gateMatrix_zero_of_odd a ha i j hodd]
  obtain ⟨h1, h2⟩ := zero_box_odd_data i j hodd
  rw [h1, h2]
  exact ⟨le_refl 0, le_refl 0⟩

/-- D5 binding: given the same-parity enclosures (the registered
follow-up campaign), the certified box contains the true gate matrix
entrywise. -/
theorem q28_hboxM_of_sameParity (a : ℝ) (ha : 0 < a)
    (hsp : ∀ i j : Fin 8, Even ((i : ℕ) + (j : ℕ)) →
      MLo_q28M i j ≤ gateMatrix (classTestFamily a ha) i j ∧
        gateMatrix (classTestFamily a ha) i j ≤ MHi_q28M i j) :
    ∀ i j : Fin 8, MLo_q28M i j ≤
        gateMatrix (classTestFamily a ha) i j ∧
      gateMatrix (classTestFamily a ha) i j ≤ MHi_q28M i j := by
  intro i j
  rcases Nat.even_or_odd ((i : ℕ) + (j : ℕ)) with hev | hod
  · exact hsp i j hev
  · exact gateMatrix_mem_zero_box_of_odd a ha i j hod

end
end C1GateMatrixBoxData
end Source
end ConnesWeilRH
