import ConnesWeilRH.Dev.C1HealthyYoshidaClosedPrefix

namespace ConnesWeilRH.Source.C1HealthyYoshidaClosedPrefix

#print axioms mem_closedBall_about_anchor_of_mem_finiteHeightZeros
#print axioms selectedOwner_laplaceAt_convolutionSquare_eq_zero_of_source_mem_closedBall_not_mem_orbit
#print axioms finiteSpectralPrefix_re_le_neg_xiMultiplicity_of_subset_finiteHeight_closedBall_control
#print axioms finiteSpectralPrefix_re_le_neg_xiMultiplicity_of_subset_finiteHeight_closedBall_square_zero_control
#print axioms finiteHeightSpectralPrefix_re_le_neg_xiMultiplicity_of_closedBall_control

end ConnesWeilRH.Source.C1HealthyYoshidaClosedPrefix
