import ConnesWeilRH.Dev.C1P2NarrowWindowCertificate

namespace ConnesWeilRH
namespace Source
namespace C1P2NarrowWindowCertificate

#print axioms narrowArchRoot_ICgate_neg
#print axioms narrowArchRoot_exists_gate_certificate
#print axioms narrowArchRoot_gate_certificate_of_margin
#print axioms narrowArchRoot_support_subset
#print axioms P2NarrowReferenceCanonicalWitness.toCanonical
#print axioms orbitGate_of_p2NarrowReferenceCanonicalWitness
#print axioms sourceRH_of_healthyDetector_p2NarrowReferenceCanonicalWitness
#print axioms not_p2NarrowReferenceCanonicalWitness_of_healthyDetectorData

end C1P2NarrowWindowCertificate
end Source
end ConnesWeilRH
