import ConnesWeilRH.Dev.C1P2BilateralProfileExit

namespace ConnesWeilRH
namespace Source
namespace C1P2BilateralProfileExit

#print axioms qw_nonneg_of_p2BilateralProfileSignWitness
#print axioms sourceRH_of_healthyDetector_p2BilateralProfileSignWitness

end C1P2BilateralProfileExit
end Source
end ConnesWeilRH
