import ConnesWeilRH.Dev.C1RouteAWeightedZeroMeasure

namespace ConnesWeilRH
namespace Dev

open Source
open Source.C1RouteAWeightedZeroMeasure

#check @weightedZeroMeasure
#check @weightedZeroMeasure_nonneg
#check @spectralTerm_re_le_weightedZeroMeasure
#check @finite_prefix_residual_re_le_weightedZeroMeasure
#check @weightedZeroMeasure_summable_of_geometric_heightMultiplicity_bound
#check @weightedZeroMeasure_le_mul_of_multiplicity_le
#check @finite_weightedZeroMeasure_sum_le_card_mul
#check @exists_spectralHeightShell_weightedZeroMeasure_bound
#check @exists_geometric_spectralHeightShell_weightedZeroMeasure_bound
#check @weightedZeroMeasure_summable_of_existing_xi_growth
#check @exists_weightedZeroMeasure_highShell_tsum_bound
#print axioms weightedZeroMeasure_nonneg
#print axioms spectralTerm_re_le_weightedZeroMeasure
#print axioms finite_prefix_residual_re_le_weightedZeroMeasure
#print axioms weightedZeroMeasure_summable_of_geometric_heightMultiplicity_bound
#print axioms weightedZeroMeasure_le_mul_of_multiplicity_le
#print axioms finite_weightedZeroMeasure_sum_le_card_mul
#print axioms exists_spectralHeightShell_weightedZeroMeasure_bound
#print axioms exists_geometric_spectralHeightShell_weightedZeroMeasure_bound
#print axioms weightedZeroMeasure_summable_of_existing_xi_growth
#print axioms exists_weightedZeroMeasure_highShell_tsum_bound

end Dev
end ConnesWeilRH
