import ConnesWeilRH.Dev.C1RouteACorrectionCoefficientBoxes2570
import ConnesWeilRH.Dev.C1RouteASignedAggregateCell2539

/-! Correction-pair centers and the 1e-28 error of records 2568/2569.
Generated by scripts/generate_correction_pair_2570.py. Membership of
the actual interpolation coefficients remains a consumer premise. -/

namespace ConnesWeilRH.Dev

noncomputable def correctionCoefficientCenter2570 (i : Fin 30) : ℂ :=
  ⟨((correctionCoefficientBox2570 i).reLo + (correctionCoefficientBox2570 i).reHi)/2,
    ((correctionCoefficientBox2570 i).imLo + (correctionCoefficientBox2570 i).imHi)/2⟩

noncomputable def correctionCoefficientError2570 (_ : Fin 30) : ℝ := 1/10^28

theorem corrBox_widths2570 (i : Fin 30) :
    (correctionCoefficientBox2570 i).reLo ≤ (correctionCoefficientBox2570 i).reHi ∧
    (correctionCoefficientBox2570 i).imLo ≤ (correctionCoefficientBox2570 i).imHi ∧
    ((correctionCoefficientBox2570 i).reHi - (correctionCoefficientBox2570 i).reLo)/2 +
      ((correctionCoefficientBox2570 i).imHi - (correctionCoefficientBox2570 i).imLo)/2 ≤
      correctionCoefficientError2570 i := by
  fin_cases i <;> norm_num [correctionCoefficientBox2570, correctionCoefficientError2570]

theorem corrCenter_mem2570 (i : Fin 30) :
    (correctionCoefficientBox2570 i).Mem (correctionCoefficientCenter2570 i) := by
  have h := corrBox_widths2570 i
  change _ ≤ (_+_)/2 ∧ (_+_)/2 ≤ _ ∧ _ ≤ (_+_)/2 ∧ (_+_)/2 ≤ _
  constructor
  · linarith [h.1]
  constructor
  · linarith [h.1]
  constructor <;> linarith [h.2.1]

theorem corrError_of_box2570 (i : Fin 30) (c : ℂ)
    (hbox : (correctionCoefficientBox2570 i).Mem c) :
    ‖c - correctionCoefficientCenter2570 i‖ ≤ correctionCoefficientError2570 i := by
  have hr : |(c - correctionCoefficientCenter2570 i).re| ≤
      ((correctionCoefficientBox2570 i).reHi - (correctionCoefficientBox2570 i).reLo)/2 := by
    change |c.re - (_+_)/2| ≤ _
    apply abs_le.mpr
    constructor <;> linarith [hbox.1, hbox.2.1]
  have hi : |(c - correctionCoefficientCenter2570 i).im| ≤
      ((correctionCoefficientBox2570 i).imHi - (correctionCoefficientBox2570 i).imLo)/2 := by
    change |c.im - (_+_)/2| ≤ _
    apply abs_le.mpr
    constructor <;> linarith [hbox.2.2.1, hbox.2.2.2]
  exact (Complex.norm_le_abs_re_add_abs_im _).trans
    ((add_le_add hr hi).trans (corrBox_widths2570 i).2.2)

end ConnesWeilRH.Dev
