import ConnesWeilRH.Dev.C1RouteAOwnerPanelNodeUpper2471
import ConnesWeilRH.Dev.C1RouteALocalCurvature2474

namespace ConnesWeilRH.Dev

/-  2475: actual-owner consumer of the cell-local curvature interface.

The node bounds are now generated by 2471.  The only remaining analytic
numeric premise is a per-cell bound on the weighted second derivative of the
actual owner sum. -/

theorem ownerPanelStripNorm_le_localCurvature2475
    (sigma radius step : ℝ) (cells : ℕ) (curvature : ℕ → ℝ)
    (hradius : 0 ≤ radius)
    (hR : ∀ i : Fin 30, ownerRad_2463 i ≤ radius)
    (hstep : 0 < step)
    (hgrid : (cells : ℝ) * step = 2 * radius)
    (hcurvature : ∀ index ∈ Finset.range cells, ∀ coordinate ∈
      Set.Icc (-radius + index * step) (-radius + (index + 1) * step),
      ‖deriv (deriv (weightedFunction2348 sigma ownerPanelSumValue_2467)) coordinate‖ ≤
        curvature index) :
    stripNorm sigma ownerPanelSumValue_2467 ≤
      compositeNodeUpper2347
        (ownerPanelNodeUpper2471 sigma radius step) step cells +
        localCurvatureRemainder2474 curvature step cells := by
  apply stripNorm_le_localCurvature2474 sigma ownerPanelSumValue_2467
    (by
      have hfamily : ∀ i : Fin 30,
          ContDiff ℝ (2 : WithTop (WithTop ℕ))
            (fun x => externalFamilyValue2344 (ownerCoef_2463 i)
              (ownerMod_2463 i) (ownerRad_2463 i) x) := fun i =>
        (externalFamilyValue2344_contDiff _ _ _ (ownerRadPos_2465 i)).of_le
          (by decide)
      simpa only [ownerPanelSumValue_2467] using
        ContDiff.sum (s := Finset.univ) (fun i _ => hfamily i))
    radius step cells (ownerPanelNodeUpper2471 sigma radius step) curvature
    hradius hstep hgrid
    (by
      intro x hx
      by_contra hxr
      apply hx
      rw [show ownerPanelSumValue_2467 x =
          ∑ i : Fin 30, externalFamilyValue2344
            (ownerCoef_2463 i) (ownerMod_2463 i)
            (ownerRad_2463 i) x by rfl]
      apply Finset.sum_eq_zero
      intro i hi
      have hnot : ¬ |x| < ownerRad_2463 i := by
        intro hinside
        apply hxr
        exact Set.Icc_subset_Icc (neg_le_neg (hR i)) (hR i)
          ⟨le_of_lt (abs_lt.mp hinside).1, le_of_lt (abs_lt.mp hinside).2⟩
      simp [externalFamilyValue2344, hnot])
    hcurvature
  intro index hindex
  exact ownerPanelNodeUpper2471_bound sigma radius step index hstep

end ConnesWeilRH.Dev
