import ConnesWeilRH.Dev.C1RouteAFallbackScalar2522
import Mathlib.Algebra.BigOperators.Fin

/-! Generated by scripts/routea_fallback_certificate_2522.py.
Every numeric upper below is proved in Lean; Python only chooses witnesses.
Safe-cell table inequalities remain open. -/

namespace ConnesWeilRH.Dev
open ConnesWeilRH.Source.C1ScaledExpRationalEnvelope
open ConnesWeilRH.Source.C1RouteAItem5Arithmetic
set_option linter.style.longLine false
set_option maxRecDepth 100000

theorem fallbackFamily0_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 0 ≤ ((455378681 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 0 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad0_2460, mod0_2460, coef0_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad0_2460, mod0_2460, coef0_2460])
  have hexp : Real.exp (ownerRad_2463 0 / 2 - 30) ≤ ((1682799925331517 : ℝ) / 5000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 0 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 0 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((1682799925331517 : ℝ) / 5000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad0_2460, mod0_2460, coef0_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 0 hsigma]
  calc
    _ ≤ ((1682799925331517 : ℝ) / 5000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 0) (ownerMod_2463 0) (ownerRad_2463 0) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad0_2460, mod0_2460, coef0_2460]
    _ ≤ ((455378681 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad0_2460, mod0_2460, coef0_2460]

theorem fallbackFamily1_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 1 ≤ ((64417981 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 1 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad1_2460, mod1_2460, coef1_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad1_2460, mod1_2460, coef1_2460])
  have hexp : Real.exp (ownerRad_2463 1 / 2 - 30) ≤ ((31784783617437 : ℝ) / 62500000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 1 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 1 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((31784783617437 : ℝ) / 62500000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad1_2460, mod1_2460, coef1_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 1 hsigma]
  calc
    _ ≤ ((31784783617437 : ℝ) / 62500000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 1) (ownerMod_2463 1) (ownerRad_2463 1) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad1_2460, mod1_2460, coef1_2460]
    _ ≤ ((64417981 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad1_2460, mod1_2460, coef1_2460]

theorem fallbackFamily2_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 2 ≤ ((6253575 : ℝ) / 128) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 2 / 2) 27
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad2_2460, mod2_2460, coef2_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad2_2460, mod2_2460, coef2_2460])
  have hexp : Real.exp (ownerRad_2463 2 / 2 - 30) ≤ ((8140130476358043 : ℝ) / 10000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 2 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 2 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((8140130476358043 : ℝ) / 10000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad2_2460, mod2_2460, coef2_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 2 hsigma]
  calc
    _ ≤ ((8140130476358043 : ℝ) / 10000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 2) (ownerMod_2463 2) (ownerRad_2463 2) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad2_2460, mod2_2460, coef2_2460]
    _ ≤ ((6253575 : ℝ) / 128) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad2_2460, mod2_2460, coef2_2460]

theorem fallbackFamily3_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 3 ≤ ((19178241 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 3 / 2) 27
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad3_2460, mod3_2460, coef3_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad3_2460, mod3_2460, coef3_2460])
  have hexp : Real.exp (ownerRad_2463 3 / 2 - 30) ≤ ((13801899241961041 : ℝ) / 10000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 3 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 3 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((13801899241961041 : ℝ) / 10000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad3_2460, mod3_2460, coef3_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 3 hsigma]
  calc
    _ ≤ ((13801899241961041 : ℝ) / 10000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 3) (ownerMod_2463 3) (ownerRad_2463 3) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad3_2460, mod3_2460, coef3_2460]
    _ ≤ ((19178241 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad3_2460, mod3_2460, coef3_2460]

theorem fallbackFamily4_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 4 ≤ ((66475 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 4 / 2) 26
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad4_2460, mod4_2460, coef4_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad4_2460, mod4_2460, coef4_2460])
  have hexp : Real.exp (ownerRad_2463 4 / 2 - 30) ≤ ((495783075102559 : ℝ) / 200000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 4 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 4 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((495783075102559 : ℝ) / 200000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad4_2460, mod4_2460, coef4_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 4 hsigma]
  calc
    _ ≤ ((495783075102559 : ℝ) / 200000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 4) (ownerMod_2463 4) (ownerRad_2463 4) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad4_2460, mod4_2460, coef4_2460]
    _ ≤ ((66475 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad4_2460, mod4_2460, coef4_2460]

theorem fallbackFamily5_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 5 ≤ ((5937717 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 5 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad5_2460, mod5_2460, coef5_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad5_2460, mod5_2460, coef5_2460])
  have hexp : Real.exp (ownerRad_2463 5 / 2 - 30) ≤ ((1918721403180919 : ℝ) / 5000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 5 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 5 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((1918721403180919 : ℝ) / 5000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad5_2460, mod5_2460, coef5_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 5 hsigma]
  calc
    _ ≤ ((1918721403180919 : ℝ) / 5000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 5) (ownerMod_2463 5) (ownerRad_2463 5) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad5_2460, mod5_2460, coef5_2460]
    _ ≤ ((5937717 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad5_2460, mod5_2460, coef5_2460]

theorem fallbackFamily6_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 6 ≤ ((1448519 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 6 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad6_2460, mod6_2460, coef6_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad6_2460, mod6_2460, coef6_2460])
  have hexp : Real.exp (ownerRad_2463 6 / 2 - 30) ≤ ((1382880021388049 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 6 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 6 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((1382880021388049 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad6_2460, mod6_2460, coef6_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 6 hsigma]
  calc
    _ ≤ ((1382880021388049 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 6) (ownerMod_2463 6) (ownerRad_2463 6) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad6_2460, mod6_2460, coef6_2460]
    _ ≤ ((1448519 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad6_2460, mod6_2460, coef6_2460]

theorem fallbackFamily7_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 7 ≤ ((461581 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 7 / 2) 27
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad7_2460, mod7_2460, coef7_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad7_2460, mod7_2460, coef7_2460])
  have hexp : Real.exp (ownerRad_2463 7 / 2 - 30) ≤ ((13801899241961041 : ℝ) / 10000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 7 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 7 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((13801899241961041 : ℝ) / 10000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad7_2460, mod7_2460, coef7_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 7 hsigma]
  calc
    _ ≤ ((13801899241961041 : ℝ) / 10000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 7) (ownerMod_2463 7) (ownerRad_2463 7) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad7_2460, mod7_2460, coef7_2460]
    _ ≤ ((461581 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad7_2460, mod7_2460, coef7_2460]

theorem fallbackFamily8_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 8 ≤ ((2812057 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 8 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad8_2460, mod8_2460, coef8_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad8_2460, mod8_2460, coef8_2460])
  have hexp : Real.exp (ownerRad_2463 8 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 8 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 8 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad8_2460, mod8_2460, coef8_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 8 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 8) (ownerMod_2463 8) (ownerRad_2463 8) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad8_2460, mod8_2460, coef8_2460]
    _ ≤ ((2812057 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad8_2460, mod8_2460, coef8_2460]

theorem fallbackFamily9_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 9 ≤ ((3645625 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 9 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad9_2460, mod9_2460, coef9_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad9_2460, mod9_2460, coef9_2460])
  have hexp : Real.exp (ownerRad_2463 9 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 9 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 9 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad9_2460, mod9_2460, coef9_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 9 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 9) (ownerMod_2463 9) (ownerRad_2463 9) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad9_2460, mod9_2460, coef9_2460]
    _ ≤ ((3645625 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad9_2460, mod9_2460, coef9_2460]

theorem fallbackFamily10_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 10 ≤ ((2785623 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 10 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad10_2460, mod10_2460, coef10_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad10_2460, mod10_2460, coef10_2460])
  have hexp : Real.exp (ownerRad_2463 10 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 10 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 10 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad10_2460, mod10_2460, coef10_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 10 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 10) (ownerMod_2463 10) (ownerRad_2463 10) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad10_2460, mod10_2460, coef10_2460]
    _ ≤ ((2785623 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad10_2460, mod10_2460, coef10_2460]

theorem fallbackFamily11_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 11 ≤ ((2459309 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 11 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad11_2460, mod11_2460, coef11_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad11_2460, mod11_2460, coef11_2460])
  have hexp : Real.exp (ownerRad_2463 11 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 11 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 11 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad11_2460, mod11_2460, coef11_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 11 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 11) (ownerMod_2463 11) (ownerRad_2463 11) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad11_2460, mod11_2460, coef11_2460]
    _ ≤ ((2459309 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad11_2460, mod11_2460, coef11_2460]

theorem fallbackFamily12_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 12 ≤ ((4271263 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 12 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad12_2460, mod12_2460, coef12_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad12_2460, mod12_2460, coef12_2460])
  have hexp : Real.exp (ownerRad_2463 12 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 12 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 12 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad12_2460, mod12_2460, coef12_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 12 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 12) (ownerMod_2463 12) (ownerRad_2463 12) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad12_2460, mod12_2460, coef12_2460]
    _ ≤ ((4271263 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad12_2460, mod12_2460, coef12_2460]

theorem fallbackFamily13_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 13 ≤ ((3834563 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 13 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad13_2460, mod13_2460, coef13_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad13_2460, mod13_2460, coef13_2460])
  have hexp : Real.exp (ownerRad_2463 13 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 13 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 13 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad13_2460, mod13_2460, coef13_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 13 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 13) (ownerMod_2463 13) (ownerRad_2463 13) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad13_2460, mod13_2460, coef13_2460]
    _ ≤ ((3834563 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad13_2460, mod13_2460, coef13_2460]

theorem fallbackFamily14_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 14 ≤ ((100971139 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 14 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad14_2460, mod14_2460, coef14_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad14_2460, mod14_2460, coef14_2460])
  have hexp : Real.exp (ownerRad_2463 14 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 14 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 14 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad14_2460, mod14_2460, coef14_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 14 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 14) (ownerMod_2463 14) (ownerRad_2463 14) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad14_2460, mod14_2460, coef14_2460]
    _ ≤ ((100971139 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad14_2460, mod14_2460, coef14_2460]

theorem fallbackFamily15_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 15 ≤ ((112994337 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 15 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad15_2460, mod15_2460, coef15_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad15_2460, mod15_2460, coef15_2460])
  have hexp : Real.exp (ownerRad_2463 15 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 15 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 15 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad15_2460, mod15_2460, coef15_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 15 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 15) (ownerMod_2463 15) (ownerRad_2463 15) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad15_2460, mod15_2460, coef15_2460]
    _ ≤ ((112994337 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad15_2460, mod15_2460, coef15_2460]

theorem fallbackFamily16_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 16 ≤ ((1067195 : ℝ) / 256) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 16 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad16_2460, mod16_2460, coef16_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad16_2460, mod16_2460, coef16_2460])
  have hexp : Real.exp (ownerRad_2463 16 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 16 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 16 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad16_2460, mod16_2460, coef16_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 16 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 16) (ownerMod_2463 16) (ownerRad_2463 16) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad16_2460, mod16_2460, coef16_2460]
    _ ≤ ((1067195 : ℝ) / 256) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad16_2460, mod16_2460, coef16_2460]

theorem fallbackFamily17_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 17 ≤ ((15473427 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 17 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad17_2460, mod17_2460, coef17_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad17_2460, mod17_2460, coef17_2460])
  have hexp : Real.exp (ownerRad_2463 17 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 17 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 17 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad17_2460, mod17_2460, coef17_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 17 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 17) (ownerMod_2463 17) (ownerRad_2463 17) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad17_2460, mod17_2460, coef17_2460]
    _ ≤ ((15473427 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad17_2460, mod17_2460, coef17_2460]

theorem fallbackFamily18_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 18 ≤ ((354011 : ℝ) / 64) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 18 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad18_2460, mod18_2460, coef18_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad18_2460, mod18_2460, coef18_2460])
  have hexp : Real.exp (ownerRad_2463 18 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 18 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 18 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad18_2460, mod18_2460, coef18_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 18 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 18) (ownerMod_2463 18) (ownerRad_2463 18) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad18_2460, mod18_2460, coef18_2460]
    _ ≤ ((354011 : ℝ) / 64) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad18_2460, mod18_2460, coef18_2460]

theorem fallbackFamily19_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 19 ≤ ((16181925 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 19 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad19_2460, mod19_2460, coef19_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad19_2460, mod19_2460, coef19_2460])
  have hexp : Real.exp (ownerRad_2463 19 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 19 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 19 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad19_2460, mod19_2460, coef19_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 19 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 19) (ownerMod_2463 19) (ownerRad_2463 19) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad19_2460, mod19_2460, coef19_2460]
    _ ≤ ((16181925 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad19_2460, mod19_2460, coef19_2460]

theorem fallbackFamily20_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 20 ≤ ((65829 : ℝ) / 4) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 20 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad20_2460, mod20_2460, coef20_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad20_2460, mod20_2460, coef20_2460])
  have hexp : Real.exp (ownerRad_2463 20 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 20 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 20 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad20_2460, mod20_2460, coef20_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 20 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 20) (ownerMod_2463 20) (ownerRad_2463 20) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad20_2460, mod20_2460, coef20_2460]
    _ ≤ ((65829 : ℝ) / 4) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad20_2460, mod20_2460, coef20_2460]

theorem fallbackFamily21_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 21 ≤ ((1305153 : ℝ) / 256) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 21 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad21_2460, mod21_2460, coef21_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad21_2460, mod21_2460, coef21_2460])
  have hexp : Real.exp (ownerRad_2463 21 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 21 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 21 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad21_2460, mod21_2460, coef21_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 21 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 21) (ownerMod_2463 21) (ownerRad_2463 21) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad21_2460, mod21_2460, coef21_2460]
    _ ≤ ((1305153 : ℝ) / 256) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad21_2460, mod21_2460, coef21_2460]

theorem fallbackFamily22_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 22 ≤ ((10282695 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 22 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad22_2460, mod22_2460, coef22_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad22_2460, mod22_2460, coef22_2460])
  have hexp : Real.exp (ownerRad_2463 22 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 22 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 22 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad22_2460, mod22_2460, coef22_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 22 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 22) (ownerMod_2463 22) (ownerRad_2463 22) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad22_2460, mod22_2460, coef22_2460]
    _ ≤ ((10282695 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad22_2460, mod22_2460, coef22_2460]

theorem fallbackFamily23_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 23 ≤ ((23046593 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 23 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad23_2460, mod23_2460, coef23_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad23_2460, mod23_2460, coef23_2460])
  have hexp : Real.exp (ownerRad_2463 23 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 23 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 23 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad23_2460, mod23_2460, coef23_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 23 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 23) (ownerMod_2463 23) (ownerRad_2463 23) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad23_2460, mod23_2460, coef23_2460]
    _ ≤ ((23046593 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad23_2460, mod23_2460, coef23_2460]

theorem fallbackFamily24_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 24 ≤ ((1260903 : ℝ) / 256) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 24 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad24_2460, mod24_2460, coef24_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad24_2460, mod24_2460, coef24_2460])
  have hexp : Real.exp (ownerRad_2463 24 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 24 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 24 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad24_2460, mod24_2460, coef24_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 24 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 24) (ownerMod_2463 24) (ownerRad_2463 24) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad24_2460, mod24_2460, coef24_2460]
    _ ≤ ((1260903 : ℝ) / 256) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad24_2460, mod24_2460, coef24_2460]

theorem fallbackFamily25_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 25 ≤ ((12459783 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 25 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad25_2460, mod25_2460, coef25_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad25_2460, mod25_2460, coef25_2460])
  have hexp : Real.exp (ownerRad_2463 25 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 25 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 25 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad25_2460, mod25_2460, coef25_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 25 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 25) (ownerMod_2463 25) (ownerRad_2463 25) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad25_2460, mod25_2460, coef25_2460]
    _ ≤ ((12459783 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad25_2460, mod25_2460, coef25_2460]

theorem fallbackFamily26_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 26 ≤ ((8148059 : ℝ) / 512) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 26 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad26_2460, mod26_2460, coef26_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad26_2460, mod26_2460, coef26_2460])
  have hexp : Real.exp (ownerRad_2463 26 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 26 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 26 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad26_2460, mod26_2460, coef26_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 26 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 26) (ownerMod_2463 26) (ownerRad_2463 26) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad26_2460, mod26_2460, coef26_2460]
    _ ≤ ((8148059 : ℝ) / 512) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad26_2460, mod26_2460, coef26_2460]

theorem fallbackFamily27_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 27 ≤ ((16180121 : ℝ) / 256) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 27 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad27_2460, mod27_2460, coef27_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad27_2460, mod27_2460, coef27_2460])
  have hexp : Real.exp (ownerRad_2463 27 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 27 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 27 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad27_2460, mod27_2460, coef27_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 27 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 27) (ownerMod_2463 27) (ownerRad_2463 27) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad27_2460, mod27_2460, coef27_2460]
    _ ≤ ((16180121 : ℝ) / 256) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad27_2460, mod27_2460, coef27_2460]

theorem fallbackFamily28_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 28 ≤ ((56184657 : ℝ) / 1024) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 28 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad28_2460, mod28_2460, coef28_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad28_2460, mod28_2460, coef28_2460])
  have hexp : Real.exp (ownerRad_2463 28 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 28 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 28 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad28_2460, mod28_2460, coef28_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 28 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 28) (ownerMod_2463 28) (ownerRad_2463 28) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad28_2460, mod28_2460, coef28_2460]
    _ ≤ ((56184657 : ℝ) / 1024) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad28_2460, mod28_2460, coef28_2460]

theorem fallbackFamily29_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma 29 ≤ ((16231919 : ℝ) / 256) := by
  have he := exp_neg_nat_interval_upper2498 (30 - ownerRad_2463 29 / 2) 28
    (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad29_2460, mod29_2460, coef29_2460]) (by norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad29_2460, mod29_2460, coef29_2460])
  have hexp : Real.exp (ownerRad_2463 29 / 2 - 30) ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
    calc
      Real.exp (ownerRad_2463 29 / 2 - 30) =
          Real.exp (-(30 - ownerRad_2463 29 / 2)) := by congr 1; ring
      _ ≤ _ := he
      _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) := by
        norm_num [ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad29_2460, mod29_2460, coef29_2460, expNegOneUpper2498, expTaylor20,
          expTaylor20Error, Finset.sum_range_succ]
  rw [ownerFamilyFallback_scalar2522 sigma 29 hsigma]
  calc
    _ ≤ ((880705750689653 : ℝ) / 2000000000000000000000000000) * familyFallbackFactor2522
        (ownerCoef_2463 29) (ownerMod_2463 29) (ownerRad_2463 29) := by
      apply mul_le_mul_of_nonneg_right hexp
      norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad29_2460, mod29_2460, coef29_2460]
    _ ≤ ((16231919 : ℝ) / 256) := by norm_num [familyFallbackFactor2522, ownerRad_2463, ownerMod_2463, ownerCoef_2463, rad29_2460, mod29_2460, coef29_2460]

noncomputable def fallbackFamilyUpper2522 (i : Fin 30) : ℝ :=
  match i.val with
  | 0 => ((455378681 : ℝ) / 1024)
  | 1 => ((64417981 : ℝ) / 1024)
  | 2 => ((6253575 : ℝ) / 128)
  | 3 => ((19178241 : ℝ) / 512)
  | 4 => ((66475 : ℝ) / 1024)
  | 5 => ((5937717 : ℝ) / 1024)
  | 6 => ((1448519 : ℝ) / 512)
  | 7 => ((461581 : ℝ) / 1024)
  | 8 => ((2812057 : ℝ) / 512)
  | 9 => ((3645625 : ℝ) / 512)
  | 10 => ((2785623 : ℝ) / 512)
  | 11 => ((2459309 : ℝ) / 512)
  | 12 => ((4271263 : ℝ) / 512)
  | 13 => ((3834563 : ℝ) / 1024)
  | 14 => ((100971139 : ℝ) / 512)
  | 15 => ((112994337 : ℝ) / 512)
  | 16 => ((1067195 : ℝ) / 256)
  | 17 => ((15473427 : ℝ) / 1024)
  | 18 => ((354011 : ℝ) / 64)
  | 19 => ((16181925 : ℝ) / 1024)
  | 20 => ((65829 : ℝ) / 4)
  | 21 => ((1305153 : ℝ) / 256)
  | 22 => ((10282695 : ℝ) / 512)
  | 23 => ((23046593 : ℝ) / 1024)
  | 24 => ((1260903 : ℝ) / 256)
  | 25 => ((12459783 : ℝ) / 512)
  | 26 => ((8148059 : ℝ) / 512)
  | 27 => ((16180121 : ℝ) / 256)
  | 28 => ((56184657 : ℝ) / 1024)
  | 29 => ((16231919 : ℝ) / 256)
  | _ => 0

theorem fallbackFamily_bound2522 (sigma : ℝ) (i : Fin 30)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyWeightedCurvatureL1_2488 sigma i ≤ fallbackFamilyUpper2522 i := by
  fin_cases i
  · exact fallbackFamily0_bound2522 sigma hsigma
  · exact fallbackFamily1_bound2522 sigma hsigma
  · exact fallbackFamily2_bound2522 sigma hsigma
  · exact fallbackFamily3_bound2522 sigma hsigma
  · exact fallbackFamily4_bound2522 sigma hsigma
  · exact fallbackFamily5_bound2522 sigma hsigma
  · exact fallbackFamily6_bound2522 sigma hsigma
  · exact fallbackFamily7_bound2522 sigma hsigma
  · exact fallbackFamily8_bound2522 sigma hsigma
  · exact fallbackFamily9_bound2522 sigma hsigma
  · exact fallbackFamily10_bound2522 sigma hsigma
  · exact fallbackFamily11_bound2522 sigma hsigma
  · exact fallbackFamily12_bound2522 sigma hsigma
  · exact fallbackFamily13_bound2522 sigma hsigma
  · exact fallbackFamily14_bound2522 sigma hsigma
  · exact fallbackFamily15_bound2522 sigma hsigma
  · exact fallbackFamily16_bound2522 sigma hsigma
  · exact fallbackFamily17_bound2522 sigma hsigma
  · exact fallbackFamily18_bound2522 sigma hsigma
  · exact fallbackFamily19_bound2522 sigma hsigma
  · exact fallbackFamily20_bound2522 sigma hsigma
  · exact fallbackFamily21_bound2522 sigma hsigma
  · exact fallbackFamily22_bound2522 sigma hsigma
  · exact fallbackFamily23_bound2522 sigma hsigma
  · exact fallbackFamily24_bound2522 sigma hsigma
  · exact fallbackFamily25_bound2522 sigma hsigma
  · exact fallbackFamily26_bound2522 sigma hsigma
  · exact fallbackFamily27_bound2522 sigma hsigma
  · exact fallbackFamily28_bound2522 sigma hsigma
  · exact fallbackFamily29_bound2522 sigma hsigma

private theorem sum30_chain2522 (f : Fin 30 → ℝ) :
    (∑ i : Fin 30, f i) = f 0 + (f 1 + (f 2 + (f 3 + (f 4 + (f 5 + (f 6 + (f 7 + (f 8 + (f 9 + (f 10 + (f 11 + (f 12 + (f 13 + (f 14 + (f 15 + (f 16 + (f 17 + (f 18 + (f 19 + (f 20 + (f 21 + (f 22 + (f 23 + (f 24 + (f 25 + (f 26 + (f 27 + (f 28 + (f 29))))))))))))))))))))))))))))) := by
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, add_zero]
  rfl

theorem familyFallback_bound2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerFamilyL1SumCurvature2488 sigma ≤ 1387328 := by
  calc
    _ ≤ ∑ i : Fin 30, fallbackFamilyUpper2522 i :=
      Finset.sum_le_sum (fun i _ => fallbackFamily_bound2522 sigma i hsigma)
    _ ≤ 1387328 := by
      rw [sum30_chain2522]
      norm_num [fallbackFamilyUpper2522]

noncomputable def ownerProductionTable2522 (index : ℕ) : ℝ :=
  if ownerProductionSafe2516 index = true then
    (ownerProductionExpTable2519 (Fin.ofNat 640 index) : ℝ)
  else 1387328

theorem fallback_hcell2522 (sigma : ℝ) (index : ℕ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ))
    (hunsafe : ¬ (196 ≤ index ∧ index ≤ 443)) :
    ownerProductionRemainderTerm2521 sigma index ≤ ownerProductionTable2522 index := by
  simpa [ownerProductionRemainderTerm2521, ownerProductionTable2522,
    ownerProductionSafe2516, hunsafe] using familyFallback_bound2522 sigma hsigma

theorem cell0_hcell2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ)) :
    ownerProductionRemainderTerm2521 sigma 0 ≤ ownerProductionTable2522 0 :=
  fallback_hcell2522 sigma 0 hsigma (by omega)

theorem ownerPanelStripNorm_le_safeTable2522 (sigma : ℝ)
    (hsigma : sigma = -(1 / 2 : ℝ) ∨ sigma = (1 / 2 : ℝ))
    (hsafe : ∀ index ∈ Finset.range 640, 196 ≤ index → index ≤ 443 →
      ownerProductionRemainderTerm2521 sigma index ≤
        (ownerProductionExpTable2519 (Fin.ofNat 640 index) : ℝ)) :
    stripNorm sigma ownerPanelSumValue_2467 ≤
      compositeNodeUpper2347
        (ownerPanelNodeUpper2471 sigma stripRadius2303 (stripRadius2303 / 320))
        (stripRadius2303 / 320) 640 +
      localCurvatureRemainder2474 ownerProductionTable2522 (stripRadius2303 / 320) 640 := by
  apply ownerPanelStripNorm_le_productionTable2521 sigma ownerProductionTable2522
  intro index hi
  by_cases hs : 196 ≤ index ∧ index ≤ 443
  · simpa [ownerProductionTable2522, ownerProductionSafe2516, hs] using
      hsafe index hi hs.1 hs.2
  · exact fallback_hcell2522 sigma index hsigma hs

end ConnesWeilRH.Dev
