import ConnesWeilRH.Dev.C1SignedVarianceIdentity

namespace ConnesWeilRH
namespace Source
namespace C1SignedVarianceIdentityAudit

open C1SignedVarianceIdentity

#print axioms finite_signed_variance_identity
#print axioms two_atom_signed_variance_identity
#print axioms two_atom_signed_variance_neg
#print axioms bipartite_double_sum_split
#print axioms finite_signed_variance_bipartite_identity
#print axioms finite_signed_variance_bipartite_neg
#print axioms exists_pos_lambda_quadratic_neg_of_bipartite_variance_gap
#print axioms finite_signed_variance_bipartite_bound_neg
#print axioms exists_pos_lambda_quadratic_neg_of_macro_atom_bounds

end C1SignedVarianceIdentityAudit
end Source
end ConnesWeilRH
