import ConnesWeilRH.Dev.C1TwoPointDifferentialAnnihilator

namespace ConnesWeilRH.Source.C1TwoPointDifferentialAnnihilator

#print axioms twoPointDerivativeAnnihilator
#print axioms laplaceAt_twoPointDerivativeAnnihilator
#print axioms twoPointDerivativeAnnihilator_laplaceAt_z1
#print axioms twoPointDerivativeAnnihilator_laplaceAt_z2
#print axioms twoPointDerivativeAnnihilator_laplaceAt_eq_zero_of_laplaceAt_eq_zero
#print axioms twoPointDerivativeAnnihilator_vanishesOn_cc20Triple
#print axioms twoPointDerivativeAnnihilator_support_subset_Icc
#print axioms twoPointDerivativeAnnihilator_square_support_subset_open_log_two
#print axioms twoPointDerivativeAnnihilator_finitePrimeSum_eq_zero
#print axioms twoPointDerivativeAnnihilator_qw_eq_neg_archimedeanTerm
#print axioms offlineZeroOrbitAnnihilator
#print axioms offlineZeroOrbitAnnihilator_laplaceAt_rho_sub_half
#print axioms offlineZeroOrbitAnnihilator_laplaceAt_one_sub_star_rho_sub_half

end ConnesWeilRH.Source.C1TwoPointDifferentialAnnihilator
