import ConnesWeilRH.Dev.C1XiCenterTwoGamma

namespace ConnesWeilRH.Source.C1XiCenterTwoGamma

#print axioms halfAnchorGaussKernel_eq_tsum
#print axioms integral_exp_neg_mul_complex_Ioi
#print axioms integral_halfAnchorGaussSeriesTerm
#print axioms integrableOn_halfAnchorGaussSeriesTerm
#print axioms integral_halfAnchorGaussPartialSum
#print axioms summable_halfAnchorGaussReciprocalSeries
#print axioms tendsto_integral_halfAnchorGaussPartialSum
#print axioms logDeriv_GammaR_eq_log_pi_add_digamma
#print axioms logDeriv_GammaR_eq_halfAnchor
#print axioms normalized_integral_gammaR_centerTwo_re_eq_archimedeanTerm

end ConnesWeilRH.Source.C1XiCenterTwoGamma
