import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSMovingBandSignedBoundTraceClass

open ConnesWeilRH
open ConnesWeilRH.Source
open ConnesWeilRH.Source.CCM25Concrete
open ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSMovingBandSignedBoundTraceClass

#check @rootSandwichedBandResponse_isTraceClassAlong_of_finiteDiagonalIntegralBound
#check @ordinaryTraceAlong_norm_le_of_finiteDiagonalIntegralBound
#check @canonicalRootSandwichedBandResponse_isTraceClassAlong_of_finiteDiagonalBound
#check @canonicalOrdinaryTraceAlong_norm_le_of_finiteDiagonalBound

#print axioms rootSandwichedBandResponse_isTraceClassAlong_of_finiteDiagonalIntegralBound
#print axioms ordinaryTraceAlong_norm_le_of_finiteDiagonalIntegralBound
#print axioms canonicalRootSandwichedBandResponse_isTraceClassAlong_of_finiteDiagonalBound
#print axioms canonicalOrdinaryTraceAlong_norm_le_of_finiteDiagonalBound
