import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSRootCompletedDetectorBoundaryTrace

open ConnesWeilRH
open ConnesWeilRH.Source
open ConnesWeilRH.Source.CCM25Concrete
open ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSRootCompletedDetectorBoundaryTrace

#check @rootCompletedDetectorTranslationBoundaryResponse
#check @rootCompletedDetectorTranslationPairData_boundaryCycle_eq
#check @rootCompletedDetectorSoninTranslationTrace_eq_boundaryTrace
#check @rootCompletedDetectorSoninTranslationTrace_eq_boundary_tsum

#print axioms rootCompletedDetectorTranslationPairData_boundaryCycle_eq
#print axioms rootCompletedDetectorSoninTranslationTrace_eq_boundaryTrace
#print axioms rootCompletedDetectorSoninTranslationTrace_eq_boundary_tsum
