import ConnesWeilRH.Source.CC20Concrete.CCM24ArchimedeanCarrier

namespace ConnesWeilRH.Source.CC20Concrete

#check ccm24MultiplicativeHaarMeasure
#check ccm24EvenAdditiveClosedSubspace
#check mem_ccm24EvenAdditiveClosedSubspace_iff_ae_even
#check lintegral_normalized_log_halfDensity_of_ae_even
#check ccm24EvenAdditiveRepresentative_ae_even
#check ccm24NormalizedLogHalfDensityRaw_enorm_sq
#check ccm24EvenToLogHalfDensity
#check norm_ccm24EvenToLogHalfDensity
#check ccm24EvenToLogHalfDensityLinearIsometry
#check ccm24LogToEvenHalfDensityRaw
#check ccm24LogToEvenHalfDensityRaw_exp
#check ccm24LogToEvenHalfDensity
#check eLpNorm_ccm24LogToEvenHalfDensityRaw
#check ccm24EvenToLogHalfDensity_rightInverse
#check ccm24EvenLogCarrierEquiv
#check ccm24EvenLogCarrierEquiv_symm_apply
#check ccm24_fourierInv_eq_reflection_fourier
#check ccm24_fourier_mem_even
#check ccm24EvenAdditiveFourier
#check ccm24EvenSchwartzSymmetrization_toLp
#check ccm24BundledEvenSchwartzToEven_coe
#check ccm24EvenSymmetrizationToEven_surjective
#check ccm24EvenSchwartzToLog_denseRange
#check ccm24ArchimedeanSourceFourier
#check ccm24ArchimedeanSourceFourier_involutive
#check ccm24ArchimedeanSourceFourier_evenSchwartz_readback
#check ccm24ArchimedeanSourceFourier_eq_hardyTitchmarsh_of_evenSchwartz
#check ccm24EvenToLogHalfDensity_bundledSchwartz_coeFn
#check ccm24Schwartz_mellinConvergent_critical
#check ccm24SchwartzFourier_mellinConvergent_critical
#check integrable_ccm24CriticalMellinLogProfile
#check ccm24_fourierTransformL2_eq_classical_toLp
#check memLp_two_fourier_of_integrable_deriv
#check integrable_ccm24CriticalMellinLogProfileChainDeriv
#check hasDerivAt_ccm24CriticalMellinLogProfile
#check integrable_deriv_ccm24CriticalMellinLogProfile
#check memLp_two_fourier_ccm24CriticalMellinLogProfile
#check ccm24EvenSchwartzCriticalMellinProfile_fourierTransformL2_eq_classical
#check ccm24_mellin_eq_fourier_criticalLogProfile
#check ccm24_mellin_one_sub_eq_fourier_criticalLogProfile
#check ccm24CriticalFourierMellinFunctionalEquation_iff_logFourier
#check memLp_ccm24EvenSchwartz_criticalMellinLogProfile
#check ccm24EvenSchwartzCriticalMellinProfileL2_eq_reflection
#check ccm24ArchimedeanScatteringPhase_eq_cosineMellinCoefficient
#check ccm24_measurePreserving_expOrderIso
#check ccm24HaarLogEquiv
#check ccm24MultiplicativeFourier
#check ccm24HaarLogEquiv_multiplicativeFourier
#check ccm24HaarToLogLinearMap_coeFn
#check ccm24LogToHaarLinearMap_coeFn
#check ccm24ArchimedeanHalfDensity_exp

#print axioms ccm24_measurePreserving_expOrderIso
#print axioms mem_ccm24EvenAdditiveClosedSubspace_iff_ae_even
#print axioms lintegral_normalized_log_halfDensity_of_ae_even
#print axioms ccm24EvenAdditiveRepresentative_ae_even
#print axioms ccm24NormalizedLogHalfDensityRaw_enorm_sq
#print axioms norm_ccm24EvenToLogHalfDensity
#print axioms ccm24EvenToLogHalfDensityLinearIsometry
#print axioms ccm24EvenLogCarrierEquiv
#print axioms ccm24_fourierInv_eq_reflection_fourier
#print axioms ccm24EvenAdditiveFourier
#print axioms ccm24EvenSchwartzSymmetrization_toLp
#print axioms ccm24BundledEvenSchwartzToEven_coe
#print axioms ccm24EvenSymmetrizationToEven_surjective
#print axioms ccm24EvenSchwartzToLog_denseRange
#print axioms ccm24ArchimedeanSourceFourier
#print axioms ccm24ArchimedeanSourceFourier_involutive
#print axioms ccm24ArchimedeanSourceFourier_evenSchwartz_readback
#print axioms ccm24ArchimedeanSourceFourier_eq_hardyTitchmarsh_of_evenSchwartz
#print axioms ccm24EvenToLogHalfDensity_bundledSchwartz_coeFn
#print axioms ccm24Schwartz_mellinConvergent_critical
#print axioms ccm24SchwartzFourier_mellinConvergent_critical
#print axioms integrable_ccm24CriticalMellinLogProfile
#print axioms ccm24_fourierTransformL2_eq_classical_toLp
#print axioms memLp_two_fourier_of_integrable_deriv
#print axioms integrable_ccm24CriticalMellinLogProfileChainDeriv
#print axioms hasDerivAt_ccm24CriticalMellinLogProfile
#print axioms integrable_deriv_ccm24CriticalMellinLogProfile
#print axioms memLp_two_fourier_ccm24CriticalMellinLogProfile
#print axioms ccm24EvenSchwartzCriticalMellinProfile_fourierTransformL2_eq_classical
#print axioms ccm24_mellin_eq_fourier_criticalLogProfile
#print axioms ccm24_mellin_one_sub_eq_fourier_criticalLogProfile
#print axioms ccm24CriticalFourierMellinFunctionalEquation_iff_logFourier
#print axioms memLp_ccm24EvenSchwartz_criticalMellinLogProfile
#print axioms ccm24EvenSchwartzCriticalMellinProfileL2_eq_reflection
#print axioms ccm24ArchimedeanScatteringPhase_eq_cosineMellinCoefficient
#print axioms ccm24HaarLogEquiv
#print axioms ccm24HaarLogEquiv_multiplicativeFourier
#print axioms ccm24ArchimedeanHalfDensity_exp

end ConnesWeilRH.Source.CC20Concrete
