import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSRootCompletedCommutatorRenewal

open ConnesWeilRH
open ConnesWeilRH.Source
open ConnesWeilRH.Source.CCM25Concrete
open ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSRootCompletedCommutatorRenewal

#check @rootCompletedBandCommutatorTransform_apply
#check @summable_finiteEulerRootCompletedCommutatorAtom
#check @sourceRootCompletedFiniteEulerCommonRightLeg_eq_commutatorRenewal
#check @summable_finiteEulerRootCompletedPairAtom
#check @finiteEulerRootCompletedPairAtom_eq_weight_smul_translation
#check @sourceRootCompletedFiniteEulerCorner_eq_commutatorRenewal
#check @sourceRootCompletedFiniteEulerCorner_eq_weightedTranslationLaw

#print axioms rootCompletedBandCommutatorTransform_apply
#print axioms summable_finiteEulerRootCompletedCommutatorAtom
#print axioms sourceRootCompletedFiniteEulerCommonRightLeg_eq_commutatorRenewal
#print axioms summable_finiteEulerRootCompletedPairAtom
#print axioms finiteEulerRootCompletedPairAtom_eq_weight_smul_translation
#print axioms sourceRootCompletedFiniteEulerCorner_eq_commutatorRenewal
#print axioms sourceRootCompletedFiniteEulerCorner_eq_weightedTranslationLaw
