import ConnesWeilRH.Source.CCM25Concrete.CCM24UnitScaleProlateAlignment

namespace ConnesWeilRH.Source

open CC20Concrete
open CCM25Concrete
open CCM25Concrete.CCM24SourceProlateTrace
open CCM25Concrete.CCM24UnitScaleProlateAlignment

#check PositiveTrace.summable_normSq_of_isTraceClassAlong_adjoint_comp_self
#check sourceProlateHilbertSchmidtFactor_adjoint_comp_self
#check sourceProlateHilbertSchmidtFactor_summable_of_isTraceClassAlong
#check sourceProlatePairDataOfTraceClassAlong_traceProduct_eq
#check sourceProlateRemainder_isCompactOperator_of_isTraceClassAlong
#check sourceProlateCommutator_isTraceClassAlong_of_remainder
#check sourceSecondSupportProlateRemainder_isTraceClassAlong_of_remainder
#check sourceThreeBranchCommutator_isTraceClassAlong_of_prolateRemainder
#check radialSupportProjection_unit
#check sourceFourierSupportProjection_unit
#check radialSupportClosedSubspace_unit
#check sourceFourierSupportClosedSubspace_unit
#check sourceSoninClosedSubspace_unit
#check sourceSoninProjection_unit
#check sourceProlateRemainder_unit

#print axioms PositiveTrace.summable_normSq_of_isTraceClassAlong_adjoint_comp_self
#print axioms sourceProlateHilbertSchmidtFactor_adjoint_comp_self
#print axioms sourceProlateHilbertSchmidtFactor_summable_of_isTraceClassAlong
#print axioms sourceProlatePairDataOfTraceClassAlong_traceProduct_eq
#print axioms sourceProlateRemainder_isCompactOperator_of_isTraceClassAlong
#print axioms sourceProlateCommutator_isTraceClassAlong_of_remainder
#print axioms sourceSecondSupportProlateRemainder_isTraceClassAlong_of_remainder
#print axioms sourceThreeBranchCommutator_isTraceClassAlong_of_prolateRemainder
#print axioms radialSupportProjection_unit
#print axioms sourceFourierSupportProjection_unit
#print axioms radialSupportClosedSubspace_unit
#print axioms sourceFourierSupportClosedSubspace_unit
#print axioms sourceSoninClosedSubspace_unit
#print axioms sourceSoninProjection_unit
#print axioms sourceProlateRemainder_unit

end ConnesWeilRH.Source
