import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSGatePhysicalLeakageTraceReduction

namespace ConnesWeilRH.Dev.CCM24FiniteSGatePhysicalLeakageTraceReductionAudit

open ConnesWeilRH Source CCM25Concrete
open CCM24FiniteSGatePhysicalLeakageTraceReduction

#check @sourceGatePhysicalForwardSymmetricResponse_eq_firstJet
#check @sourceGatePhysicalLeakageCrossingResponse_eq_neg_sourceBandGramResponse
#check @ordinaryTraceAlong_leakage_eq_neg_sourceBandGram
#check @sourceGatePhysicalForwardSymmetricResponse_isTraceClassAlong
#check @sourceGatePhysicalLeakageCrossingResponse_isTraceClassAlong
#check @ordinaryTraceAlong_lowerFactorGaugedResponse_eq_firstJet_add_leakage
#check @lowerFactorGaugedResponse_trace_norm_le_supportEnergy_add_leakage
#check @exists_uniform_lowerFactorGaugedTraceBound_iff_leakageTraceBound

#print axioms sourceGatePhysicalForwardSymmetricResponse_eq_firstJet
#print axioms sourceGatePhysicalLeakageCrossingResponse_eq_neg_sourceBandGramResponse
#print axioms ordinaryTraceAlong_leakage_eq_neg_sourceBandGram
#print axioms sourceGatePhysicalForwardSymmetricResponse_isTraceClassAlong
#print axioms sourceGatePhysicalLeakageCrossingResponse_isTraceClassAlong
#print axioms ordinaryTraceAlong_lowerFactorGaugedResponse_eq_firstJet_add_leakage
#print axioms lowerFactorGaugedResponse_trace_norm_le_supportEnergy_add_leakage
#print axioms exists_uniform_lowerFactorGaugedTraceBound_iff_leakageTraceBound

end ConnesWeilRH.Dev.CCM24FiniteSGatePhysicalLeakageTraceReductionAudit
