/-
Copyright (c) 2026 ConnesWeilRH contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierMovingMomentColumnSelector

namespace ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierMovingMomentColumnSelectorAudit

open ConnesWeilRH.Source.CCM25Concrete
open CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierMovingMomentColumnSelector

#check @onePrimeBoundaryMomentColumn
#check @onePrimeBoundaryMomentColumn_apply
#check @arithmeticVisiblePrimeSequence
#check @arithmeticVisiblePrimeSequence_isPrime
#check @tendsto_ccm24PrimeEulerCoefficient_arithmeticVisiblePrimeSequence
#check @exists_uniformly_bounded_movingSource_of_eventually_column_norm_gt
#check @noExistsUniformOldCarrierDomination_of_eventually_column_norm_gt
#check @noExistsUniformOldCarrierDomination_of_eventually_arithmeticPrime_column_norm_gt

#print axioms onePrimeBoundaryMomentColumn
#print axioms onePrimeBoundaryMomentColumn_apply
#print axioms arithmeticVisiblePrimeSequence
#print axioms arithmeticVisiblePrimeSequence_isPrime
#print axioms tendsto_ccm24PrimeEulerCoefficient_arithmeticVisiblePrimeSequence
#print axioms exists_uniformly_bounded_movingSource_of_eventually_column_norm_gt
#print axioms noExistsUniformOldCarrierDomination_of_eventually_column_norm_gt
#print axioms noExistsUniformOldCarrierDomination_of_eventually_arithmeticPrime_column_norm_gt

end ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierMovingMomentColumnSelectorAudit
