import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSReflectedRootEnergy

open ConnesWeilRH
open ConnesWeilRH.Source
open ConnesWeilRH.Source.CCM25Concrete
open ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSReflectedRootEnergy

#check @norm_archimedeanHardyTitchmarshOperator_le_one
#check @seminorm_zero_zero_reflection_eq
#check @reflectedTranslatedCompactRootPairData_left_basisEnergy_le
#check @reflectedTranslatedCompactRootPairData_right_basisEnergy_le
#check @sourceSecondSupportCompactRootPairData_left_basisEnergy_le
#check @sourceSecondSupportCompactRootPairData_right_basisEnergy_le
#check @sourceSecondSupportCompactRootPairData_left_basisEnergy_le_original
#check @sourceSecondSupportCompactRootPairData_right_basisEnergy_le_original

#print axioms norm_archimedeanHardyTitchmarshOperator_le_one
#print axioms seminorm_zero_zero_reflection_eq
#print axioms reflectedTranslatedCompactRootPairData_left_basisEnergy_le
#print axioms reflectedTranslatedCompactRootPairData_right_basisEnergy_le
#print axioms sourceSecondSupportCompactRootPairData_left_basisEnergy_le
#print axioms sourceSecondSupportCompactRootPairData_right_basisEnergy_le
#print axioms sourceSecondSupportCompactRootPairData_left_basisEnergy_le_original
#print axioms sourceSecondSupportCompactRootPairData_right_basisEnergy_le_original
