/-
Copyright (c) 2026 ConnesWeilRH contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierAntiresonantInteriorFrameLossRadialPhysicalOwnerFiniteSEndpointAlignment

namespace ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierAntiresonantInteriorFrameLossRadialPhysicalOwnerFiniteSEndpointAlignmentAudit

open ConnesWeilRH.Source
open ConnesWeilRH.Source.CCM25Concrete
open ConnesWeilRH.Source.CCM25Concrete.AntiresonantFrameLossRadialPhysicalOwnerFiniteSEndpointAlignment

#check @parameterizedFourierSupportProjection_one_eq_target
#check @parameterizedSoninProjection_one_eq_target
#check @parameterizedProlateRemainder_one_eq_target
#check @radialSignedPhysicalOwner_one_eq_targetThreeBranch_add_boundary
#check @suffixPrimeTranslationProjectionCommutator_one_eq_targetThreeBranch_add_boundary

#print axioms parameterizedFourierSupportProjection_one_eq_target
#print axioms parameterizedSoninProjection_one_eq_target
#print axioms parameterizedProlateRemainder_one_eq_target
#print axioms radialSignedPhysicalOwner_one_eq_targetThreeBranch_add_boundary
#print axioms suffixPrimeTranslationProjectionCommutator_one_eq_targetThreeBranch_add_boundary

end ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierAntiresonantInteriorFrameLossRadialPhysicalOwnerFiniteSEndpointAlignmentAudit
