import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSGatePhysicalCausalDualFrameCorner

namespace ConnesWeilRH.Dev.CCM24FiniteSGatePhysicalCausalDualFrameCornerAudit

open ConnesWeilRH Source CCM25Concrete
open CCM24FiniteSGatePhysicalCausalDualFrameCorner

#check @finiteEulerDualFrame_adjoint_comp_radialSupport_eq_self
#check @finiteEulerDualFrame_adjoint_comp_transport_eq_ambientGramReadback
#check @finiteEulerTargetCommutatorResponse_eq_causalDualFrameRootCorner

#print axioms finiteEulerDualFrame_adjoint_comp_radialSupport_eq_self
#print axioms finiteEulerDualFrame_adjoint_comp_transport_eq_ambientGramReadback
#print axioms finiteEulerTargetCommutatorResponse_eq_causalDualFrameRootCorner

end ConnesWeilRH.Dev.CCM24FiniteSGatePhysicalCausalDualFrameCornerAudit
