/-
Copyright (c) 2026 Connes-WeilRH contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierAntiresonantInteriorFiniteHorizonCoboundary

namespace ConnesWeilRH
namespace Source
namespace CCM25Concrete

open CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierAntiresonantInteriorFiniteHorizonCoboundary

#check @finiteAntiresonantAlternatingPolynomial
#check @finiteAntiresonantAlternatingPolynomial_comp_id_add
#check @norm_finiteAntiresonantAlternatingPolynomial_le
#check @finiteHorizonAntiresonantCoboundaryReadout
#check @finiteHorizonAntiresonantCoboundaryReadout_comp_scaled_id_add
#check @finiteHorizonAntiresonantCoboundaryReadout_comp_scaled_id_add_of_terminal
#check @norm_finiteHorizonAntiresonantCoboundaryReadout_le
#check @primeEulerAmbientLossFactor_eq_negativeTranslation
#check @primeEulerAmbientLossFactor_adjoint_eq_positiveTranslation
#check @suffixActualBandCompleteCoupledAmbientTarget
#check @suffixActualBandCompleteCoupledAmbientTarget_comp_newFrame
#check @suffixActualBandFiniteHorizonCoboundaryReadout
#check @suffixActualBandFiniteHorizonCoupledTail
#check @suffixActualBandFiniteHorizonCoboundaryReadout_comp_lossAdjoint
#check @suffixActualBandFiniteHorizonCoboundaryReadout_comp_rawColumn
#check @suffixActualBandFiniteHorizonCoboundaryReadout_comp_rawColumn_of_terminal
#check @norm_suffixActualBandFiniteHorizonCoboundaryReadout_le

#print axioms finiteAntiresonantAlternatingPolynomial
#print axioms finiteAntiresonantAlternatingPolynomial_comp_id_add
#print axioms norm_finiteAntiresonantAlternatingPolynomial_le
#print axioms finiteHorizonAntiresonantCoboundaryReadout
#print axioms finiteHorizonAntiresonantCoboundaryReadout_comp_scaled_id_add
#print axioms finiteHorizonAntiresonantCoboundaryReadout_comp_scaled_id_add_of_terminal
#print axioms norm_finiteHorizonAntiresonantCoboundaryReadout_le
#print axioms primeEulerAmbientLossFactor_eq_negativeTranslation
#print axioms primeEulerAmbientLossFactor_adjoint_eq_positiveTranslation
#print axioms suffixActualBandCompleteCoupledAmbientTarget
#print axioms suffixActualBandCompleteCoupledAmbientTarget_comp_newFrame
#print axioms suffixActualBandFiniteHorizonCoboundaryReadout
#print axioms suffixActualBandFiniteHorizonCoupledTail
#print axioms suffixActualBandFiniteHorizonCoboundaryReadout_comp_lossAdjoint
#print axioms suffixActualBandFiniteHorizonCoboundaryReadout_comp_rawColumn
#print axioms suffixActualBandFiniteHorizonCoboundaryReadout_comp_rawColumn_of_terminal
#print axioms norm_suffixActualBandFiniteHorizonCoboundaryReadout_le

end CCM25Concrete
end Source
end ConnesWeilRH
