/-
Copyright (c) 2026 ConnesWeilRH contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierFixedSourceMomentObstruction

namespace ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierFixedSourceMomentObstructionAudit

open ConnesWeilRH.Source.CCM25Concrete
open CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierFixedSourceMomentObstruction

#check @tendsto_onePrimeBoundaryMoment_norm_on_newSuffixFrame_of_uniformOldCarrierDomination
#check @noExistsUniformOldCarrierDomination_of_fixedSourceMoment_not_tendsto_zero
#check @noExistsUniformOldCarrierDomination_of_fixedSourceMoment_lowerBound
#check @noExistsUniformOldCarrierDomination_of_movingSourceMoment_lowerBound

#print axioms tendsto_onePrimeBoundaryMoment_norm_on_newSuffixFrame_of_uniformOldCarrierDomination
#print axioms noExistsUniformOldCarrierDomination_of_fixedSourceMoment_not_tendsto_zero
#print axioms noExistsUniformOldCarrierDomination_of_fixedSourceMoment_lowerBound
#print axioms noExistsUniformOldCarrierDomination_of_movingSourceMoment_lowerBound

end ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierFixedSourceMomentObstructionAudit
