/-
Copyright (c) 2026 ConnesWeilRH contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSCompletedJuliaComponentKernel

namespace ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaComponentKernelAudit

open ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSCompletedJuliaComponentKernel

#check suffixEulerFrameAmbientBoundaryAnalysis_norm_eq_leftCoDefect
#check componentReadout_rawAdjoint_norm_le_leftCoDefect
#check componentReadout_rawAdjoint_eq_zero_of_analysis_eq_zero
#check componentReadout_rawAdjoint_eq_zero_of_leftCoDefect_eq_zero
#check componentReadout_mismatchAdjoint_eq_zero_of_analysis_eq_zero
#check componentReadout_mismatchAdjoint_eq_zero_of_leftCoDefect_eq_zero
#check uniformComponentReadout_rawAdjoint_norm_le_leftCoDefect
#check uniformComponentReadout_rawAdjoint_eq_zero_of_analysis_eq_zero
#check uniformComponentReadout_mismatchAdjoint_eq_zero_of_analysis_eq_zero

#print axioms suffixEulerFrameAmbientBoundaryAnalysis_norm_eq_leftCoDefect
#print axioms componentReadout_rawAdjoint_norm_le_leftCoDefect
#print axioms componentReadout_rawAdjoint_eq_zero_of_analysis_eq_zero
#print axioms componentReadout_rawAdjoint_eq_zero_of_leftCoDefect_eq_zero
#print axioms componentReadout_mismatchAdjoint_eq_zero_of_analysis_eq_zero
#print axioms componentReadout_mismatchAdjoint_eq_zero_of_leftCoDefect_eq_zero
#print axioms uniformComponentReadout_rawAdjoint_norm_le_leftCoDefect
#print axioms uniformComponentReadout_rawAdjoint_eq_zero_of_analysis_eq_zero
#print axioms uniformComponentReadout_mismatchAdjoint_eq_zero_of_analysis_eq_zero

end ConnesWeilRH.Dev.CCM24FiniteSCompletedJuliaComponentKernelAudit
