import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSGatePhysicalCanonicalCompletedKernel

open ConnesWeilRH Source CCM25Concrete
open CCM24FiniteSGatePhysicalCanonicalCompletedKernel

#check @finiteEulerCanonicalCompletedKernelScalar
#check @finiteEulerCanonicalCompletedKernelScalar_eq_directLeakageDiagonal
#check @finiteEulerCanonicalCompletedKernelScalar_eq_obliqueShearFullKernelScalar
#check @finiteEulerCanonicalCompletedKernelDiagonalSeries
#check @ordinaryTraceAlong_targetCommutator_eq_canonicalCompletedKernelDiagonalSeries
#check @finiteEulerCanonicalCompletedKernelDiagonalSeries_eq_obliqueShearFullKernelTrace
#check @ordinaryTraceAlong_completedKernelLeakageResponse_eq_canonicalCompletedKernelDiagonalSeries

#print axioms finiteEulerCanonicalCompletedKernelScalar_eq_directLeakageDiagonal
#print axioms finiteEulerCanonicalCompletedKernelScalar_eq_obliqueShearFullKernelScalar
#print axioms ordinaryTraceAlong_targetCommutator_eq_canonicalCompletedKernelDiagonalSeries
#print axioms finiteEulerCanonicalCompletedKernelDiagonalSeries_eq_obliqueShearFullKernelTrace
#print axioms
  ordinaryTraceAlong_completedKernelLeakageResponse_eq_canonicalCompletedKernelDiagonalSeries
