/-
Copyright (c) 2026 Connes-WeilRH contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ConnesWeilRH.Source.CCM25Concrete.CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierAntiresonantInteriorOneStepTargetSize

namespace ConnesWeilRH
namespace Source
namespace CCM25Concrete

open
  CCM24FiniteSCompletedJuliaRawPhysicalOldCarrierAntiresonantInteriorOneStepTargetSize

#check @suffixActualBandCompleteCoupledAmbientTarget_eq_interior_comp_frameAdjoint
#check @norm_suffixActualBandCompleteCoupledAmbientTarget_eq_interior
#check @norm_suffixScalar_smul_completeCoupledAmbientTarget_le_eight
#check @finiteHorizonAntiresonantCoboundaryReadout_one
#check @routeScaledCompleteCoupledAmbientTarget
#check @routeFiniteHorizonReadout_withHorizon_one_eq_scaledTarget
#check @SuffixCompleteCoupledRouteUniformScaledTargetBound
#check @norm_routeScaledCompleteCoupledAmbientTarget_eq_div
#check @exists_routeUniformScaledTargetBound_of_pointwise
#check @exists_routeUniformScaledTargetBound_of_pairedAdjointCoboundaryEnvelope
#check @scaled_even_terminal_eq_inner_scaledTarget
#check @norm_scaled_even_terminal_le_of_scaledTargetBound

#print axioms suffixActualBandCompleteCoupledAmbientTarget_eq_interior_comp_frameAdjoint
#print axioms norm_suffixActualBandCompleteCoupledAmbientTarget_eq_interior
#print axioms norm_suffixScalar_smul_completeCoupledAmbientTarget_le_eight
#print axioms finiteHorizonAntiresonantCoboundaryReadout_one
#print axioms routeScaledCompleteCoupledAmbientTarget
#print axioms routeFiniteHorizonReadout_withHorizon_one_eq_scaledTarget
#print axioms norm_routeScaledCompleteCoupledAmbientTarget_eq_div
#print axioms exists_routeUniformScaledTargetBound_of_pointwise
#print axioms exists_routeUniformScaledTargetBound_of_pairedAdjointCoboundaryEnvelope
#print axioms scaled_even_terminal_eq_inner_scaledTarget
#print axioms norm_scaled_even_terminal_le_of_scaledTargetBound

end CCM25Concrete
end Source
end ConnesWeilRH
