"""Import the 120 exact base coefficient endpoints from record 2338."""
import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "results/2338_exact_interpolation_repair.json"
TARGET = ROOT / "ConnesWeilRH/Dev/C1RouteABaseCoefficientBoxes2540.lean"


def integer(value):
    high, low = divmod(abs(value), 10**60)
    if not high:
        return str(value)
    sign, operation = ("-", "-") if value < 0 else ("", "+")
    return f"({sign}{high} * 10^60 {operation}\n            {low})"


def render():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    rows = data["coefficient_rows"]
    assert len(rows) == 30
    lines = [
        "import ConnesWeilRH.Dev.C1RouteAIntervalAlgebra",
        "",
        "/-! Exact record-2338 base coefficient rectangles.",
        "Generated by scripts/generate_center_node_2540.py.",
        "Source SHA256: " + hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        "The literals define rectangles; exact-owner membership is not asserted. -/",
        "",
        "namespace ConnesWeilRH.Dev",
        "",
        "noncomputable def baseCoefficientBox2540 (index : Fin 30) : ComplexRect2427 :=",
        "  match index.val with",
    ]
    for index, row in enumerate(rows):
        assert row["index"] == index
        values = []
        for component in ("real", "imag"):
            lo, hi = (Fraction(row["ideal_base_coefficient"][component][side])
                      for side in ("lower_exact", "upper_exact"))
            assert lo <= hi
            values.extend((lo, hi))
        lines.append(f"  | {index} =>")
        for slot, (field, value) in enumerate(zip(("reLo", "reHi", "imLo", "imHi"), values)):
            prefix = "      { " if slot == 0 else "        "
            suffix = " }" if slot == 3 else ""
            lines.append(prefix + field + f" := ({integer(value.numerator)} : ℝ) /\n"
                         f"          {integer(value.denominator)}" + suffix)
    lines.extend(["  | _ => ComplexRect2427.zero", "", "end ConnesWeilRH.Dev", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        assert TARGET.read_text(encoding="utf-8") == expected
        print("EXACT_2338_ENDPOINT_IMPORT_PASS 120 endpoints")
    else:
        TARGET.write_text(expected, encoding="utf-8", newline="\n")
        print("Generated", TARGET.name)


if __name__ == "__main__":
    main()
